### ISSUE TITLE
client starts 3-4 times

### ISSUE THREAD

**Issue by Inge1234567890** [isaackogan/TikTokLive#101]
Hello Isaac,

i don´t know why this happen, but everytime i want to start this code, it connects 3-4 times the client.

The Print on Line 26: 
Connected to Room ID: None

https://pastebin.com/wrX8vgPy

**Comment by isaackogan** [comment]
Please fix the formatting, your code is unreadable

**Comment by isaackogan** [comment]
You are starting the client within the while loop, that's what causes it to start multiple times, I believe
