### ISSUE TITLE
Running client without blocking mainloop as in Tkinter

### ISSUE THREAD

**Issue by GalangLatief** [isaackogan/TikTokLive#102]
Hi,

The docs says to use await client.start() instead of run().  But there is no example of how to use it. Is there any? i have try implementing await client.start() but it says "coroutine never awaited"

Thank You.

**Comment by GalangLatief** [comment]
> Hi,
> 
> The docs says to use await client.start() instead of run(). But there is no example of how to use it. Is there any? i have try implementing await client.start() but it says "coroutine never awaited"
> 
> Thank You.

EDIT: Solved, see "Using with Pygame" example

**Comment by slambingo** [comment]
Hello, does this example still exist? I can't find anything called that.
