### ISSUE TITLE
Get stuck when proxied

### ISSUE THREAD

**Issue by BILINGBALL** [isaackogan/TikTokLive#108]
**Describe the bug**

client: TikTokLiveClient = TikTokLiveClient(
    unique_id="@www.kbs.comy",
    trust_env=True,
    **({
        "proxies" : {
            "all://" : "http://localhost:10809",
        },
    }
    )
)

**Additional context**
When I use proxies like this, the api got stucked and log nothing out, waiting for long. 

Maybe websocket can not be proxied. But I have to use vpn. 
Can this problem be solved?

Regards!

**Comment by isaackogan** [comment]
More info, stacktraces, etc. :(
