### ISSUE TITLE
ViewerUpdateEvent dosn´t work

### ISSUE THREAD

**Issue by dalef-ef** [isaackogan/TikTokLive#110]
ViewerUpdateEvent dosn´t work. Dont update the Viewer Count.

ViewerUpdateEvent (named in Readme) calls in Code "ViewerCountUpdateEvent" but this also dosn´t work.

**Comment by isaackogan** [comment]
![image](https://user-images.githubusercontent.com/65869106/224429291-c62b8606-3af9-4dec-9c22-5071c799e5b3.png)

As recently as yesterday I can confirm that the event does work. What is your code.

**Comment by dalef-ef** [comment]
<img width="726" alt="Test" src="https://user-images.githubusercontent.com/28683829/224468452-6362c6b0-1000-4e28-ab82-cb7b25bbbf3f.PNG">

**Comment by dalef-ef** [comment]
<img width="729" alt="Test" src="https://user-images.githubusercontent.com/28683829/224468616-9c19cff3-612f-496d-8d83-1ad9a932bff8.PNG">

**Comment by dalef-ef** [comment]
I have forgot to update to v5. Sry for that. an thx
