### ISSUE TITLE
Improve client workflow for connect and disconnects

### ISSUE THREAD

**Issue by gutomaia** [isaackogan/TikTokLive#111]
**Is your feature request related to a problem? Please describe.**

Improve the overwall connect/disconnect workflow of a client. 

Although we do have methods for switching between all the client states. I was unable to put the client on the ready state after a disconnect of an LiveNotFound exceptions.

**Describe the solution you'd like**

I was thinking an in a "autoconnect" argument on both the "connect"  and "start" methods.  Goal is to keep the connection/disconnection workflow in charge of an inner deamon of the client. Client it self must retry in a consistent retry interval. Also, interval could be incremented with a function argument. 

Well, if that is not an option. What do you think of at least an example on how to achieve that.

**Describe alternatives you've considered**

So far what I've I'm trying is, i've encapsulated the client, and in my connect method I'm retrying when the attempt have failed.
```

class Tiktok:

    def __init__(self, user):
        self.user = user
        self.loop = asyncio.new_event_loop()
        self.loop.set_exception_handler(self.exception_handler)
        self.client = TikTokLiveClient(unique_id=user, loop=self.loop)

    async def connect(self):
        while True:
            if self.client.connected:
                print('connected:', self.user)
                await asyncio.sleep(5)
            if self.client.connecting:
                print('connecting:', self.user)
                await asyncio.sleep(1)
            elif not self.client.connected and not self.client.connecting:
                print('connect: ', self.user)
                try:
                    await self.client.start()
                except LiveNotFound:
                    self.client.stop()
                    await asyncio.sleep(60)

```

Then, I just try to connect with all clients with:

```
async def start(loop):
    for user, client in clients.items():
        asyncio.run_coroutine_threadsafe(client.connect(), loop)
    while True:
        await asyncio.sleep(10)

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    loop.run_until_complete(start(loop))

```

**Comment by E-This** [comment]
Good day, what could be the reason for this error? I've been struggling with this issue and I want to run it please help :(
![ekran](https://github.com/isaackogan/TikTokLive/assets/89603093/dc34d790-2150-4a2e-8466-23a3960a7034)
