### ISSUE TITLE
Exception has occurred: InitialCursorMissing 

### ISSUE THREAD

**Issue by mechineay** [isaackogan/TikTokLive#120]
I recently used the library without any errors or exceptions, but today I made some changes to comply with the new 5.0.8 update. Specifically, I changed the method name "gift.streaking" to 'repeat_end' since I only use the gift and comments events. However, I'm now encountering an error and I have no idea what's causing it.

`Exception has occurred: InitialCursorMissing
Missing cursor in initial fetch response.
  File "\ttok-req_db.py", line 79, in <module>
    client.run()
TikTokLive.types.errors.InitialCursorMissing: Missing cursor in initial fetch response.`

`\lib\site-packages\TikTokLive\proto\utilities.py:21: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  webcast_data.ParseFromString(obj)`

**Comment by isaackogan** [comment]
@mechineay I believe this was a library-wide issue. Please confirm.
