### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by Reystud** [isaackogan/TikTokLive#121]
Hello,
Im sorry to open an issue on this problem again but it seems the microservice is down ?
I don't really understand how you handle session connection but i imagine you are sharing an api key with the original JS repo, does tiktok blocking this api time to time ? 

Thank you again for the work :)

Christian

**Comment by isaackogan** [comment]
Hi,

No, it gets ddosed from time to time.

Migrating to a protected host (finally), now.
Isaac

**Comment by Reystud** [comment]
Thank you.

Also, do you have a donation page or anything where we can support the project ?

**Comment by isaackogan** [comment]
Hi,

https://www.buymeacoffee.com/isaackogan

Isaac

**Comment by simeonhalsey** [comment]
Yes, im also getting: google.protobuf.message.DecodeError: Error parsing message

Thanks Issac, for jumping on this so quick :)
