### ISSUE TITLE
EnvelopeEvent is not showing any data

### ISSUE THREAD

**Issue by simeonhalsey** [isaackogan/TikTokLive#125]
EnvelopeEvent is not showing any data, only working on version TikTokLive==4.3.8 for what I can tell.

Not giving an error message that I can capture either.

Tried on Windows 10, python 3.7 and 3.11

**Comment by simeonhalsey** [comment]
Pretty sure last working version was Version: 4.5.2 so maybe something after that broke it :)

**Comment by isaackogan** [comment]
> Pretty sure last working version was Version: 4.5.2 so maybe something after that broke it :)

Would have been updated due to a TikTok proto change. Will look into fixing in newest version.

**Comment by isaackogan** [comment]
Gonna close this for now. 

Falls under https://github.com/isaackogan/TikTokLive/issues/157 & will be fixed.
