### ISSUE TITLE
could you add proxy support for websocket connection

### ISSUE THREAD

**Issue by qraccess** [isaackogan/TikTokLive#129]
**Is your feature request related to a problem? Please describe.**
The region I am currently in requires a proxy to access TikTok. However, I have noticed that the current proxies do not support websockets. Is it possible to add support for websockets?

        :param proxies: Enable proxied requests by turning on forwarding for the HTTP "proxies" argument. Websocket connections will NOT be proxied.

**Comment by isaackogan** [comment]
Maybe, potentially.

Via https://github.com/fullstackwang/python-ftx/blob/master/ftx/wsapi.py, using the websocket-client library.

I'm not a huge fan though, as it is just wrapping sync calls in an executor...

**Comment by isaackogan** [comment]
Answer: No, not until `websockets` supports it.
