### ISSUE TITLE
On Subscribe Event

### ISSUE THREAD

**Issue by shalevc1098** [isaackogan/TikTokLive#133]
The Node.JS version of this library already has this event, and it would be really useful if this library would have it too. I made a TikTok server using Node.JS, but currently migrating to Python, because the Node.JS library is refusing to connect to the lives, even when polling is enabled. Thanks in advance

**Comment by isaackogan** [comment]
Hi, you are mistaken.

The NodeJS version does not have that event. It has it in the code, but it hasn't worked in over six months. It requires login cookies, and I am committed to TikTokLive being strictly no login.

Isaac

**Comment by shalevc1098** [comment]
> Hi, you are mistaken.
> 
> The NodeJS version does not have that event. It has it in the code, but it hasn't worked in over six months. It requires login cookies, and I am committed to TikTokLive being strictly no login.
> 
> Isaac

why it requires login?
