### ISSUE TITLE
TikTokLive.types.errors.FailedParseUserHTML: Your IP or country might be blocked by TikTok.

### ISSUE THREAD

**Issue by aviongeno** [isaackogan/TikTokLive#134]
**Describe the bug**
TikTokLive.types.errors.FailedParseUserHTML: Your IP or country might be blocked by TikTok.

It looks like zerody put out an update yesterday. Maybe this code just needs to update with the latest zerody base?

**Comment by zerodytrash** [comment]
The change i made is already implemented here in https://github.com/isaackogan/TikTokLive/commit/726350d2eb383196b5a08ea4c7fa55a10dfb6a92 .
It just needs a new release.

**Comment by isaackogan** [comment]
> The change i made is already implemented here in [726350d](https://github.com/isaackogan/TikTokLive/commit/726350d2eb383196b5a08ea4c7fa55a10dfb6a92) . It just needs a new release.

Did I never release my update? WHOOPS

**Comment by S3RO-tonino** [comment]
Hi, I still have this problem, can i do sometingh to avoid it??

**Comment by dragosite** [comment]
I am getting this too, on the example website as well?

**Comment by botea14** [comment]
TikTokLive.types.errors.FailedParseUserHTML: Your IP or country might be blocked by TikTok.

got this error starting this morning. like 10hours ago i used TikTokLive while streaming with no issues.

**Comment by SamiFala** [comment]
Same here

**Comment by jonaswndl** [comment]
Had the same issue today aswell
