### ISSUE TITLE
Will there ever be profile picture download?

### ISSUE THREAD

**Issue by spdesmith** [isaackogan/TikTokLive#135]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We'd want to be able to download the user profile so that we can display it along with their username

**Describe alternatives you've considered**
Tried using python to scrape it off the internet but tiktok blocks us from doing that after about 15 seconds

**Comment by isaackogan** [comment]
If you are blocked, use proxies.
