### ISSUE TITLE
Error parsing meassage

### ISSUE THREAD

**Issue by masumr** [isaackogan/TikTokLive#139]
When i am going connect tiktok livestream at this we face this error *Error parsing meassage* and throw this type of error -
![image_2023_08_25T08_22_12_255Z](https://github.com/isaackogan/TikTokLive/assets/17784661/33b40f38-4db3-4bf0-bf33-e6c5841b9437)
![image_2023_08_25T08_22_26_074Z](https://github.com/isaackogan/TikTokLive/assets/17784661/dc04cda1-f997-4d76-ae11-664d31bdef7a)

**Comment by amir-viva** [comment]
@isaackogan , Sir could you please solve this issue ?
I've also faced the same problem in my project.
After connecting multiple accounts (say 8 to10) at a time asynchronously , Got the error.

**Comment by amir-viva** [comment]
Or, at least any idea, why I got this error ?
How to overcome the error?
Thanks @isaackogan

**Comment by richiec77** [comment]
Any update on this issue?

**Comment by amir-viva** [comment]
@isaackogan sir, is there any thing from you,  which would make us optimistic. We're eagerly waiting for your response.

**Comment by isaackogan** [comment]
Most likely a desync between the current Protobuf and the library's. In terms of a fix, one is coming. Please refer to https://github.com/isaackogan/TikTokLive/issues/157 for information.
