### ISSUE TITLE
TikTokLive.types.errors.SignatureRateLimitReached even if only starting one connection

### ISSUE THREAD

**Issue by PWSMarcello** [isaackogan/TikTokLive#140]
Hi, 
I'm not sure if it's a bug, but I often (pretty much always) get the following error when starting the inital connection to a live.

TikTokLive.types.errors.SignatureRateLimitReached: You have hit the rate limit for starting connections. Try again in 1551 seconds. Catch this error & access its attributes (retry_after, reset_time) for data on when you can request next.

Am I doing something wrong in my python script? I am only observing one user, my script checks until he is live, then starts client.run() then gets the livestream and on live end goes back to the loop. am I keeping old sessions active somehow?

Thanks in advance - I love this project!

**Comment by isaackogan** [comment]
How are you checking if he is live

**Comment by PWSMarcello** [comment]
> How are you checking if he is live

I do a get on 'https://www.tiktok.com/api-live/user/room/?aid=1988&region=DE&sourceType=54&uniqueId=<USERID> every minute and check the user status in the returned data. If successful I wait 60s and then do a client.run()

**Comment by Geczy** [comment]
@PWSMarcello can you share the repo

**Comment by isaackogan** [comment]
> > How are you checking if he is live
> 
> I do a get on 'https://www.tiktok.com/api-live/user/room/?aid=1988&region=DE&sourceType=54&uniqueId= every minute and check the user status in the returned data. If successful I wait 60s and then do a client.run()

It is likely you are calling the connect method too frequently :)
