### ISSUE TITLE
ConnectEvent

### ISSUE THREAD

**Issue by jh0nny69** [isaackogan/TikTokLive#141]
Been using TikTokLive for a few months now and i love this project!
The last few days I am not even able to connect to the room!! 
I tried some changes but the script runs forever without ever connecting to the room!
Not sure whats the ussue, If it is tiktok blocking but just letting know the community about my issue!
2 Days and i was not able to connect to the room once !
Thanks for the time and much love from Portugal <3

**Comment by isaackogan** [comment]
Hi, I need some more info. Perhaps code snippets or error logs.
