### ISSUE TITLE
Messages from some users are not displayed

### ISSUE THREAD

**Issue by GGTEC** [isaackogan/TikTokLive#142]
Comments from certain users (always from the same users) are not received, the comment appears normally in the platform chat but does not appear when executed in the code

**To Reproduce**
Just run the example code

**Screenshots**
[Video](
https://github.com/isaackogan/TikTokLive/assets/23065725/a6c4e52f-a0c8-429b-bfdf-d5c8e689ccab
) 

**Desktop (please complete the following information):**
 - Windowns 11
 - VSCODE
 - Python 3.11.4
 - TikTokLive 5.0.8

**Smartphone (please complete the following information):**
- Not relevant as devices and users are random

**Comment by spdesmith** [comment]
Same thing is happening for me, people are frustrated

**Comment by isaackogan** [comment]
Hey, this issue is known.

Please see https://github.com/isaackogan/TikTokLive/pull/145 for the fix you can implement in a fork. 

This lib will have a fix in early-mid December pending a rewrite: https://github.com/isaackogan/TikTokLive/issues/157

**Comment by GGTEC** [comment]
Sorry, I made the PR and didn't close it here,

**Comment by isaackogan** [comment]
> Sorry, I made the PR and didn't close it here,

Hilarious that I did not notice you made the PR
