### ISSUE TITLE
URGENT! Nobody can connect it right now. We get HttpRequestException: Request was unsuccessful [403]

### ISSUE THREAD

**Issue by mubgit** [isaackogan/TikTokLive#149]
**Describe the bug**

**To Reproduce**

**Expected behavior**
We get HttpRequestException: Request was unsuccessful [403] error.

**Screenshots**
[https://imgur.com/y1cC4lj](https://imgur.com/y1cC4lj)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by isaackogan** [comment]
Fixed.
