### ISSUE TITLE
i need a little help :)

### ISSUE THREAD

**Issue by serdaralkanmedia** [isaackogan/TikTokLive#150]
**### i want to check  whatcher user is following streamer or not  while events running ? is it possible ?**

from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import CommentEvent, ConnectEvent, GiftEvent, Gift, Dict
from TikTokLive.types.objects import User , UserInfo
import pyautogui
import keyboard
import time

client: TikTokLiveClient = TikTokLiveClient(unique_id="@alyona.klv", enable_detailed_gifts="yes")

@client.on("connect")
async def on_connect(_: ConnectEvent):
    print("Connected to Room ID:", client.room_id)

async def on_comment(event: CommentEvent):    
    time.sleep(0.2) 
   
    izleyici :  User = User(unique_id = "@{event.user.unique_id}")
 
    if izleyici.is_following == 1 :
 
        if event.comment == "gaz" or event.comment == "Gaz":
            hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
            hwnd.activate()
            keyboard.press('up')
            time.sleep(1)
            keyboard.release("up")
            print(f"{event.user.nickname} -> {event.comment}")
        elif event.comment == "fren" or event.comment == "Fren":
            hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
            hwnd.activate()
            keyboard.press('down')
            time.sleep(0.25)
            keyboard.release("down")
            print(f"{event.user.nickname} -> {event.comment}")
        elif event.comment == "sol" or event.comment == "Sol":
            hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
            hwnd.activate()
            keyboard.press('left')
            time.sleep(0.25)
            keyboard.release("left")
            print(f"{event.user.nickname} -> {event.comment}")
        elif event.comment == "sağ"  or event.comment == "sag"  or event.comment == "Sag" or event.comment == "Sağ" :
            hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
            hwnd.activate()
            keyboard.press('right')
            time.sleep(0.25)
            keyboard.release("right")
            print(f"{event.user.nickname} -> {event.comment}")
        elif event.comment == "Farlar"  or event.comment == "farlar" :
            hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
            hwnd.activate()
            keyboard.press('l')
            keyboard.release("l")
            print(f"{event.user.nickname} -> {event.comment}")
        elif event.comment == "sol sinyal"  or event.comment == "Sol sinyal" :
            hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
            hwnd.activate()
            keyboard.press('q')
            keyboard.release("q")
            print(f"{event.user.nickname} -> {event.comment}")
        elif event.comment == "sağ sinyal"  or event.comment == "sag sinyal"  or event.comment == "Sag sinyal" or event.comment == "Sağ sinyal" :
            hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
            hwnd.activate()
            keyboard.press('e')
            keyboard.release("e")
            print(f"@{event.user.unique_id} -> {event.comment}")
    else : 
          print(f"@{event.user.unique_id} ->Not FOLLOWING {izleyici.is_following}")      

async def on_gift(event: GiftEvent):
    if event.gift.info.name == "TikTok" :
        hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
        hwnd.activate()
        keyboard.press('g')
        time.sleep(0.1)
        keyboard.release("g")
        time.sleep(0.1)
        keyboard.press('g')
        time.sleep(0.1)
        keyboard.release("g")
        time.sleep(0.1)
        keyboard.press('g')
        time.sleep(0.5)
        keyboard.release("g")
    elif event.gift.info.name == "GG" :
        hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
        hwnd.activate()
        keyboard.press('space')
        time.sleep(4)
        keyboard.release("space")

    elif event.gift.info.name == "Rose" :
        hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
        hwnd.activate()
        keyboard.press('up')
        time.sleep(4)
        keyboard.release("up")

    elif event.gift.info.name == "Blue Bead" :
        hwnd = pyautogui.getWindowsWithTitle("@serdarhocam - Google Chrome")[0]
        hwnd.activate()
        keyboard.press('left')
        time.sleep(3)
        keyboard.release("left")

client.add_listener("gift", on_gift)

client.add_listener("comment", on_comment)

if __name__ == '__main__':
    client.run()

**Comment by isaackogan** [comment]
Currently no, but we may add a way to check in the future. You can use the code from the library to implement your own check function. For now, this is out of scope, sorry.
