### ISSUE TITLE
WARNING - Failed to fetch room id from Webcast

### ISSUE THREAD

**Issue by muhee93** [isaackogan/TikTokLive#152]
Hello!

We have been seeing this warning message **(WARNING - Failed to fetch room id from Webcast)** with some of the livestreams that we are working with. Can someone help me understand why and when this message is dropped and what could be the probable way to solve this?

We are trying to catch the livestream data, video, comments and stream activities but this is causing the event data to be missing.

Would appreciate if a prompt response is received.

Thanks in advance.

**Comment by maikegelei** [comment]
me too

**Comment by isaackogan** [comment]
Due to the current approach which is being overhauled.

See https://github.com/isaackogan/TikTokLive/issues/137
