### ISSUE TITLE
Get the points and battle status when a live battle is started between people

### ISSUE THREAD

**Issue by pd2871** [isaackogan/TikTokLive#153]
Hi,
Thank you for this great library. Currently, I want to know few things regarding live battle between people in tiktok.

Suppose when a battle is started between two people, I want to get the points they have in every second or custom time interval. 
(Example: 1st guy can have 20 points whereas his opponent can have 30 points at the same time).
Also, it will be a great feature if we can get to know who has won and who has lost the battle at the end of the battle.

Please help me on how to get these live points and which user has win/lost the battle. 
Any answer will be helpful :)

**Comment by isaackogan** [comment]
Hi!!

You should be able to get the points by listening to the `MicBattleUpdateEvent` which will tell you both points and when the battle ends.

The raw payload probably says who won too, but, you can track who has the most points and when it ends, use that to calculate a winner.

**Comment by pd2871** [comment]
Hi @isaackogan ,
Thank you for answering the question. It really helped.

I have a suggestion. It would be really helpful if you can update the readme with the expected data structure for each events so that we can know what kind of data structure to expect. I was looking into nose JS version of this repo and they have mentioned expected data structure for each event. So, I am hoping you will update it like that as well.

**Comment by pd2871** [comment]
Hi @isaackogan ,
Thank you for answering the question. It really helped.

I have a suggestion. It would be really helpful if you can update the readme with the expected data structure for each events so that we can know what kind of data structure to expect. I was looking into node JS version of this repo and they have mentioned expected data structure for each event. So, I am hoping you will update it like that as well.

**Comment by isaackogan** [comment]
Hi.

The reason I don't do that is that docs are provided on the homepage that already do this for all classes in the library: https://isaackogan.github.io/TikTokLive/.
