### ISSUE TITLE
 Unable to Capture Event Data after few minutes later 

### ISSUE THREAD

**Issue by masumr** [isaackogan/TikTokLive#156]
**Library Version:** TikTokLive 5.0.8
**Issue:**  After approximately 10-20 minutes of using the TikTok Live package, I encounter an issue where I am unable to capture event data using the **await start()** function. This behavior is unexpected and affects the functionality of the library.

Would appreciate if a prompt response is received.

Thanks in advance.

**Comment by isaackogan** [comment]
Duplicate of https://github.com/isaackogan/TikTokLive/issues/137
