### ISSUE TITLE
Maintenance Hiatus & Future Plans

### ISSUE THREAD

**Issue by isaackogan** [isaackogan/TikTokLive#157]
Hello,

I recognize that there are _a lot_ of issues with the library right now. My current plans are as follows, in order of priority:

1. Redo the library to support ALL protobuf definitions (monolithic task)
2. Add dynamic updating of protobuf for future
3. Add backwards compatibility to allow for 3 months deprecation of old system
4. Update documentation to reflect new definitions (massive task)
5. Swap `websockets` library with `websocket-client` library for websockets
6. Add proxy support for the whole library
7. Release a beta version & have people test on it
8. Try to replicate current bugs on beta version & patch the ones that remain
9. Replace the unreleased 'live check' on master branch with a better, less intrusive version.

I don't expect this to be released or even _started_ until _December_. I am a university student, and TikTokLive (Python) is a solo project. The sheer volume of changes on top of being a full-time student (currently with a 4.0 GPA), having a part-time job, and personal responsibilities / social life, make an update utterly impossible right now.

December is when I get my break. I look forward to using everything I've learned in the last year to deliver the best version of TikTokLive to date.

Isaac

**Comment by atyrode** [comment]
Thanks Isaac for dedicating so much time into this project. Is there any pointers we can refer to if we'd like to contribute and help you bring this project forward? Where can we get started?

**Comment by MerlimarCode** [comment]
Ditto I'd like to help out if I can.

**Comment by Synthintel0** [comment]
try to add webcastCaptionMessage #176

**Comment by isaackogan** [comment]
this thread aged poorly
