### ISSUE TITLE
Quality issues with mp4 download and possible solution

### ISSUE THREAD

**Issue by eliich** [isaackogan/TikTokLive#160]
Hello I notice when trying to download the mp4 through the client, the quality is kinda bad. Quality is way better just simply using ffmpeg with cdn link or using this repo: https://github.com/Michele0303/tiktok-live-recorder.

**Comment by isaackogan** [comment]
Well, we use FFMPEG in the library. It's just that the lowest quality is selected by default. You can up the quality yourself...
