### ISSUE TITLE
Missing cursor in initial fetch response

### ISSUE THREAD

**Issue by masumr** [isaackogan/TikTokLive#162]
Hi, we used in *TikTokLive 4.5.2* package and  when it starts to  capture event  data we are facing error *Missing cursor in initial fetch response* . 
![image](https://github.com/isaackogan/TikTokLive/assets/17784661/286ca489-f962-4a54-9d61-8b3922d71131)

**Comment by albertofernandezs** [comment]
I have the same problem.

**Comment by freeacger** [comment]
I have the same problem + 1

**Comment by wg200202** [comment]
I have the same problem + 1

**Comment by isaackogan** [comment]
Fixed.
