### ISSUE TITLE
The library won't work for private accounts

### ISSUE THREAD

**Issue by burakdev01** [isaackogan/TikTokLive#168]
I use this library to record streams, and live gifts/comments. However, it won't work for private accounts.

To record private account streams that I follow, I use YT-DLP to get HLS URL passing cookies file, that I extracted from my browser, like so: _yt-dlp -e -g https://www.tiktok.com/.../live --cookies cookies.txt_

Can we achieve the same in this library? It should connect to TikTok servers with a provided cookie file. I've tried passing http_headers and http_params as options to TikTokLiveClient but that didn't work.

My apologies if my English isn't good, but I hope I've managed to express myself clearly.

**Comment by isaackogan** [comment]
The lib already supports passing your own cookies to the HTTP client and websocket. Please check the source, it's not well documented. But it's there.

**Comment by PascalVD** [comment]
@isaackogan can you explain how to use it ? beceause i suspect that that is the reason why i do not receive all comments ..

**Comment by isaackogan** [comment]
Hi, see `client.web.set_session_id` for info in v6.0.0
