### ISSUE TITLE
Missing sound when download live

### ISSUE THREAD

**Issue by cao-minh-duc** [isaackogan/TikTokLive#172]
**Describe the bug**
It seam like missing sound of livestream when you download
**To Reproduce**
followed exactly download example
**Expected behavior**
I should have sound after download

**Comment by isaackogan** [comment]
This depends on your configuration; you can modify ffmpeg values in v6.0.0.

**Comment by minearithmeticop** [comment]
@cao-minh-duc did you solve it?

**Comment by minearithmeticop** [comment]
@isaackogan can you show example of configuration?
i try to modify code in ffmpeg config input and output until i got this

ffmpeg -y -loglevel error -i [https://pull-flv-l1-sg01.tiktokcdn.com/stage/stream-2420614390903996462_ld.flv\?expire\=1711450621\&sign\=167355f8f0cd184464266c490e64bfc0](https://pull-flv-l1-sg01.tiktokcdn.com/stage/stream-2420614390903996462_ld.flv/?expire\=1711450621\&sign\=167355f8f0cd184464266c490e64bfc0) -i [https://pull-flv-l1-sg01.tiktokcdn.com/stage/stream-2420614390903996462.flv\?expire\=1711450621\&sign\=1516caaca9010a98e6810a5f38e5a877\&only_audio\=1](https://pull-flv-l1-sg01.tiktokcdn.com/stage/stream-2420614390903996462.flv/?expire\=1711450621\&sign\=1516caaca9010a98e6810a5f38e5a877\&only_audio\=1) -c:v h264 -c:a aac trainingmc.com.mp4

but finally i didn't get sound in video

**Comment by minearithmeticop** [comment]
i already solve it
