### ISSUE TITLE
Some people when they write on the comment i do not receive it in the python script 

### ISSUE THREAD

**Issue by PascalVD** [isaackogan/TikTokLive#175]
**Describe the bug**
For some users that are not in private and they wrote some in the comment (chat) i do not receive it on the comment Python . 
I check with all the user that facing this issue and they are not in private ... i create new accounts but cannot reproduce the issue .. i have a friend that can test if you want he facing this issue 

**To Reproduce**
problem is facing with some users not for all , i create 3 new accounts but cannot reproduce and in my lave a lot of users facing the issue 

**Expected behavior**
When some people set some comment in the chat the comment do not show with the python script 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22
 - Version 22

**Additional context**

**Comment by isaackogan** [comment]
Hi. To fix this, pass a session id! In v6.0.0, you can do this with `client.web.set_session_id`
