### ISSUE TITLE
READ ME: MAJOR LIBRARY NEWS

### ISSUE THREAD

**Issue by isaackogan** [isaackogan/TikTokLive#178]
# TikTokLive News 

After a LONG wait, TikTokLive is getting a new completely remade version ~~__in the next 72h__.~~ I'm just wrapping up the last of my tasks.

The new version is a supercharged TikTokLive, with >2600 lines of **just** TikTok event definitions, over 4x the original version. We went from around 20% coverage to >95% after this update. 

I've also built a tool to **automatically update** the proto when TikTok makes a change. All in all, TikTokLive has never been as powerful as it's about to get.

If you want to support my late-night 1:30am open source, consider paying for my coffee / future sleep-debt-related medical bills: https://www.buymeacoffee.com/isaackogan

**Comment by Geczy** [comment]
did that release yet?

**Comment by isaackogan** [comment]
Almost!
