### ISSUE TITLE
Error: google.protobuf.message.DecodeError: Truncated message.

### ISSUE THREAD

**Issue by rozeren** [isaackogan/TikTokLive#179]
Hello im coding on a Mac if that's what's causing this error, ive ran the script a few times but now I end up with this : google.protobuf.message.DecodeError: Truncated message.
Anyone know why? 

This is the code `from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import CommentEvent, ConnectEvent

# Instantiate the client with the user's username
client: TikTokLiveClient = TikTokLiveClient(unique_id="@")

# Define how you want to handle specific events via decorator
@client.on("connect")
async def on_connect(_: ConnectEvent):
    print("Connected to Room ID:", client.room_id)

# Notice no decorator?
async def on_comment(event: CommentEvent):
    print(f"{event.user.nickname} -> {event.comment}")

# Define handling an event via a "callback"
client.add_listener("comment", on_comment)

if __name__ == '__main__':
    # Run the client and block the main thread
    # await client.start() to run non-blocking
    client.run()`

**Comment by isaackogan** [comment]
Hi, please re-open this issue if it occurs in v6.0.0, which was released today.
