### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 14: invalid start byte

### ISSUE THREAD

**Issue by Superheroff** [isaackogan/TikTokLive#186]
### Describe the bug
    def tiktok_live(self, room_id, internal_ext="", cursor=""):
        url = f"https://webcast.us.tiktok.com/webcast/im/fetch/?aid=1988&app_language=zh-Hant-TW&app_name=tiktok_web" \
              f"&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_platform=Win32" \
              f"&browser_version=5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20" \
              f"%28KHTML%2C%20like%20Gecko%29%20Chrome%2F121.0.0.0%20Safari%2F537.36&cookie_enabled=true&cursor" \
              f"={cursor}&debug=false&device_id=&device_platform=web" \
              f"&did_rule=3&fetch_rule=2&history_comment_count=6&history_comment_cursor=7336717295970224898&host" \
              f"=https%3A%2F%2Fwebcast.us.tiktok.com&identity=audience&internal_ext={internal_ext}&last_rtt" \
              f"=2232&live_id=12&resp_content_type=protobuf&room_id={room_id}&screen_height=864" \
              f"&screen_width=1536&tz_name=Asia%2FShanghai&version_code=270000&msToken" \
              f"=0f_JF_3VYp3Vn0b1M9_E0B4BTLiCDBuHCjR6flT8d9vHHLrnooKctkUDAZNzwLvHMdQlykYV7B8UFna9Iyb2Q" \
              f"-4AQCft2kPmdzW3l2ZK-CCFZEN2f0qIMFQY6Lhh5xZR5XKZnF1NSr4q"

        self.headers["Referer"] = "https://www.tiktok.com/"
        self.headers["Origin"] = "https://www.tiktok.com"
        self.headers["Host"] = "webcast.us.tiktok.com"
        self.headers["Content-Type"] = "application/x-www-form-urlencoded; charset=UTF-8"
        try:
            res = requests.get(url, headers=self.headers, proxies=self.proxy)

            print(res.content)
            data = deserialize_message("WebcastResponse", res.content)
            print(data)
            return data
        except Exception as e:
            print("请检查代理IP是否可用", e)

data = b'\n\xb6\x02\n\x0bRoomMessage\x12\x9c\x02\n*\n\rSystemMessage\x10\xa3\xae\xcb\xb7\xc1\xc4\xdf\xdb\x17\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeee \x97\xff\xfa\xb5\xde1\x12\xeb\x01\xe6\xad\xa1\xe8\xbf\x8e\xe4\xbd\xbf\xe7\x94\xa8 TikTok \xe7\x9b\xb4\xe6\x92\xad\xef\xbc\x81\xe5\x9c\xa8\xe6\xad\xa4\xe9\xa0\x90\xe7\xa5\x9d\xe6\x82\xa8\xe8\x88\x87\xe5\x85\xb6\xe4\xbb\x96\xe4\xba\xba\xe5\x8d\xb3\xe6\x99\x82\xe4\xba\x92\xe5\x8b\x95\xe6\x84\x89\xe5\xbf\xab\xe3\x80\x82\xe7\x9b\xb4\xe6\x92\xad\xe4\xb8\xbb\xe5\xbf\x85\xe9\xa0\x88\xe5\xb9\xb4\xe6\xbb\xbf 18 \xe6\xad\xb2\xe6\x89\x8d\xe8\x83\xbd\xe9\x96\x8b\xe5\xa7\x8b\xe7\x9b\xb4\xe6\x92\xad\xef\xbc\x8c\xe8\xa7\x80\xe7\x9c\xbe\xe4\xb9\x9f\xe5\xbf\x85\xe9\xa0\x88\xe5\xb9\xb4\xe6\xbb\xbf 18 \xe6\xad\xb2\xe6\x89\x8d\xe8\x83\xbd\xe5\x84\xb2\xe5\x80\xbc\xe4\xb8\xa6\xe9\x80\x81\xe5\x87\xba\xe7\xa6\xae\xe7\x89\xa9\xe3\x80\x82\xe8\xab\x8b\xe5\x8b\x99\xe5\xbf\x85\xe9\x81\xb5\xe5\xae\x88\xe6\x88\x91\xe5\x80\x91\xe7\x9a\x84\xe3\x80\x8a\xe7\xa4\xbe\xe7\xbe\xa4\xe8\x87\xaa\xe5\xbe\x8b\xe5\x85\xac\xe7\xb4\x84\xe3\x80\x8b\xe3\x80\x828\x01\x18\xc2\xf2\xc8\xb7\xc1\xc4\xdf\xdb\x17\n\xd2\x08\n\x17WebcastLiveIntroMessage\x12\xac\x08\n#\n\x17WebcastLiveIntroMessage\x10\xab\x96\x88\xbc\xee\xea\x93\xd9e\x10\xab\x96\x88\xbc\xee\xea\x93\xd9e\x18\x01"\x96\x01Lives at least twice/day! Relaxation, satisfaction, and positive energy watching names being written- some in calligraphy! Come sit a spell\xe2\x80\xa6\xf0\x9f\x98\x8a\xf0\x9f\x8c\xb9*\xb9\x06\x08\x86\x88\x9c\xb2\xc0\xae\xdd\xf0a\x1a<\xe2\x9c\xa8\xf0\x9d\x94\x8f\xf0\x9d\x94\xac\xf0\x9d\x94\xaf\xf0\x9d\x94\x9e\xe2\x9c\xa8\xf0\x9d\x94\x8f\xf0\x9d\x94\xac\xf0\x9d\x94\xb3\xf0\x9d\x94\xa2\xf0\x9d\x94\xb0\xe2\x9c\xa8\xf0\x9d\x94\x9c\xf0\x9d\x94\xac\xf0\x9d\x94\xb2\xe2\x9c\xa8J\x9c\x05\n\xc3\x01https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/325bbc8ded3271edfd97dbf2e88ded05~c5_100x100.webp?lk3s=a5d48078&x-expires=1709139600&x-signature=avCxXOqezZkKmQlQvifv3BtV9vE%3D\n\xc5\x01https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/325bbc8ded3271edfd97dbf2e88ded05~c5_100x100.webp?lk3s=a5d48078&x-expires=1709139600&x-signature=qUU1e0QYn11yX%2FiqHMYI66WDnoI%3D\n\xc9\x01https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/325bbc8ded3271edfd97dbf2e88ded05~c5_100x100.jpeg?lk3s=a5d48078&x-expires=1709139600&x-signature=YcF%2BvuikuieaMX%2FHuOt%2F6EybWuU%3D\x12@100x100/tos-useast5-avt-0068-tx/325bbc8ded3271edfd97dbf2e88ded05\x82\x02\x00\xf2\x02LMS4wLjABAAAAF1x0UcAQFKdPCvfTHPISj0lold66oaBQgAnXjb3kmXCJdVYgsT98g6x2J0O4d4id0\x01:\x1e\x08\x02\xaa\x01\x19\x08\x02\x12\x0fpm_mt_hostlabel\x1a\x04HostB\x02en\x18\xab\x96\x88\xbc\xee\xea\x93\xd9e\n\xe1\x01\n\x12WebcastRoomMessage\x12\xc0\x01\n\xb8\x01\n\x12WebcastRoomMessage\x10\xab\x96\x8c\xbc\xd0\xc4\xb3\xeee\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeee \xc1\x9c\xf3\xae\x060\x01B\x85\x01\n pm_mt_LIVE_commentFiltered_notif\x12QSome comments in this LIVE were filtered to protect the community\xe2\x80\x99s experience.\x1a\x0e\n\t#ff8CE7FF \x90\x03\x12\x01  \x01\x18\xab\x96\x8c\xbc\xd0\xc4\xb3\xeee\n\xa2\x10\n\x12WebcastChatMessage\x12\xff\x0f\nO\n\x12WebcastChatMessage\x10\xae\x96\xc8\x82\xe4\xd8\xb6\xeee\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeee \xf2\xbf\xdc\xb5\xde10\x01H\x02P\x02z\x07useast5\xb0\x01\x05\xb8\x01\x02\xc0\x01\x02\xc8\x01\x8c\xbd\xdc\xb5\xde1\x12\xf2\x0b\x08\xaa\x88\x91\xea\x81\xe3\xfa\x8fc\x1a\x0ehollycrosby655J\xa7\x06\n\xc4\x01https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7142857328298033194~tplv-tiktok-shrink:72:72.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=z7jozzujcP8K38wfQ1j1oH0N4eo%3D\n\xb6\x01https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7142857328298033194~c5_100x100.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=XNrthgnjNxQBro0T0OOXPLE4dkQ%3D\n\xb6\x01https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7142857328298033194~c5_100x100.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=42vo3sPMeJWYQZZTOs2udm6gnOI%3D\n\xb6\x01https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7142857328298033194~c5_100x100.jpeg?lk3s=a5d48078&x-expires=1709143200&x-signature=gHucW5wp57QIm3rnZuv5S2uAoNo%3D\x123100x100/tos-useast5-avt-0068-tx/7142857328298033194R\xbe\x04\n\xbd\x01https://p16-sign.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7142857328298033194~tplv-tiktokx-compress_quality_30:64:64.webp?x-expires=1708992000&x-signature=RL0SnvxSO%2F2TOZUL5%2FE2jfC67gw%3D\n\xbb\x01https://p19-sign.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7142857328298033194~tplv-tiktokx-compress_quality_30:64:64.webp?x-expires=1708992000&x-signature=mAE5jMiwFt7eShvY%2BD0pGP0yXpY%3D\n\xbd\x01https://p16-sign.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7142857328298033194~tplv-tiktokx-compress_quality_30:64:64.jpeg?x-expires=1708992000&x-signature=Po%2BuO%2BHgaYGvKWyozDyFlT2FLEQ%3D\xb2\x01\x04\x08L\x10\x11\xba\x01\x00\x82\x02\x00\xb2\x02\x0ehollycrosby655\xf2\x02LMS4wLjABAAAA-U9q801anlbYuC6G0dkoK_KrwyML9jiU_-4_IdvQV-kevgJo4xrWi9P2gR8x-ggX\x1a\x06Dallasr\x02en\x92\x01\x00\x9a\x01\x14\n\x0euser_type_rule\x10\xa0\x8d\x06\x9a\x01\x18\n\x11community-flagged\x10\x91\x8e\x86\x01\x9a\x01\x1a\n\x0ecommentator_id\x10\xaa\x88\x91\xea\x81\xe3\xfa\x8fc\x9a\x01\x12\n\x07default\x10\xf0\xc0\xce\xda\xd3\xc9\x84\x03\x9a\x01\x10\n\x0bdefault_app\x10\x90N\x9a\x01\x11\n\x06rankV3\x10\xc0\xfd\xb0\xdf\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0fttp_rule_rerank\x10\xc0\xfd\xb0\xdf\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0etimestamp_desc\x10\xc0\xaf\xd9\x91\xb2\xe5\xcc\xae\x01\x9a\x015\n*tikcast_community_comment_18866_v7_r655069\x10\xc0\xfd\xb0\xdf\xd3\xc9\x84\x03\x9a\x01:\n/tikcast_community_comment_18866_v7_r655069_desc\x10\xc0\xfd\xb0\xdf\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0fidc_rule_rerank\x10\xd8\xa9\xba\xf2\xd3\xc9\x84\x03\x9a\x01\x16\n\x0bv13_r712088\x10\xd8\xa9\xba\xf2\xd3\xc9\x84\x03\x9a\x01\x16\n\x0bv12_r702075\x10\xd8\xa9\xba\xf2\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0fidc_rule_rerank\x10\xd8\xa9\xba\xf2\xd3\xc9\x84\x03\xa2\x01\x01\x00\x18\xae\x96\xc8\x82\xe4\xd8\xb6\xeee0\x01\n\x9e\x0b\n\x12WebcastChatMessage\x12\xfb\n\x12\x9a\t\xb2\x01\x06\x08\xa8L\x10\x93\x19\xf2\x02LMS4wLjABAAAA_VxBtK3C6veG5Noa0Y34WcW7JE3GR6DiYp-0lulfkTJPAUC11BfZiHz01NFC1V4g\x08\x85\x88\xb3\xc6\xbe\xce\xed\x9e_J\xf9\x04\n\xc2\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/ec603d1b179cdd7ec6df6ebd6350e127~tplv-tiktok-shrink:72:72.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=LkBtkq5yAQ9Rm8EVMycORem1waw%3D\n\xbc\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/ec603d1b179cdd7ec6df6ebd6350e127~c5_100x100.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=1d%2B%2BEg7Ak%2B03FtZ7w6A6%2BXumCjM%3D\n\xb4\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/ec603d1b179cdd7ec6df6ebd6350e127~c5_100x100.jpeg?lk3s=a5d48078&x-expires=1709143200&x-signature=3Xf3FehYdroMJeew6zYZsuJFQr4%3D\x12<100x100/tos-maliva-avt-0068/ec603d1b179cdd7ec6df6ebd6350e127\xba\x01\x00\x82\x02\x00\xb2\x02\x11helloadepaula7777\x1a\x11helloadepaula7777R\x8c\x03\n\xc2\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/ec603d1b179cdd7ec6df6ebd6350e127~tplv-tiktokx-compress_quality_30:64:64.webp?x-expires=1708992000&x-signature=PGf1p2oxXj1mT9GZkq7EMHNIg1Y%3D\n\xc4\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/ec603d1b179cdd7ec6df6ebd6350e127~tplv-tiktokx-compress_quality_30:64:64.jpeg?x-expires=1708992000&x-signature=GTyt2krh%2FKxgi1klhZaRuGg7bIg%3D\x1a\x07Hello\xc3\xa1r\x02vi\x92\x01\x00\x9a\x01\x12\n\x07default\x10\xb0\xdf\xa6\xdd\xd3\xc9\x84\x03\x9a\x01\x10\n\x0bdefault_app\x10\x90N\x9a\x01\x18\n\rbatch_rank_v1\x10\xc2\x8d\xcb\xea\xd3\xc9\x84\x03\x9a\x01\x1b\n\x10v16_r808359_desc\x10\xec\xf9\xad\xe0\xd3\xc9\x84\x03\x9a\x01\x16\n\x0bv16_r808359\x10\x93\xff\x90\xdc\xd3\xc9\x84\x03\xa2\x01\x01\x00\nNz\x06maliva\xb0\x01\x04\n\x12WebcastChatMessage\x10\x86\x96\xc7\xc4\xaa\xdc\xb6\xeee\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeee0\x01P\x02 \xdb\xe8\xdc\xb5\xde1H\x02\xb8\x01\x02\xc0\x01\x02\xc8\x01\xd3\xe5\xdc\xb5\xde1\x18\x86\x96\xc7\xc4\xaa\xdc\xb6\xeee0\x01\n\x98\x0b\n\x12WebcastChatMessage\x12\xf5\n\x9a\x01\x12\x10\xb0\xdf\xa6\xdd\xd3\xc9\x84\x03\n\x07default\x9a\x01\x10\n\x0bdefault_app\x10\x90N\x9a\x01\x18\n\rbatch_rank_v1\x10\xc2\x8d\xcb\xea\xd3\xc9\x84\x03\x9a\x01\x1b\n\x10v16_r808359_desc\x10\xed\xf9\xad\xe0\xd3\xc9\x84\x03\x9a\x01\x16\n\x0bv16_r808359\x10\x92\xff\x90\xdc\xd3\xc9\x84\x03\xa2\x01\x01\x00\nN\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeee \xe7\xe8\xdc\xb5\xde1\xb8\x01\x02\xb0\x01\x04\xc0\x01\x02\n\x12WebcastChatMessage\x10\x86\x96\xde\x9a\xac\xdc\xb6\xeee0\x01H\x02P\x02z\x06maliva\xc8\x01\x90\xb7\xdc\xb5\xde1\x12\x8f\t\x08\x86\x88\xc2\xd0\xf9\xbd\xdf\xbdeJ\xf5\x04\n\xc2\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/d4d0761ed6606f91f15e367aba8ca9a4~tplv-tiktok-shrink:72:72.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=3STsHgj87UIXpyBdBTJYSDm98ck%3D\n\xb6\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/d4d0761ed6606f91f15e367aba8ca9a4~c5_100x100.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=ZM%2FACaXmzuGjvjFFBRMjkKql4zM%3D\n\xb6\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/d4d0761ed6606f91f15e367aba8ca9a4~c5_100x100.jpeg?lk3s=a5d48078&x-expires=1709143200&x-signature=2mmZDWGlDCGvGP%2F5kAHV4rLLNcA%3D\x12<100x100/tos-maliva-avt-0068/d4d0761ed6606f91f15e367aba8ca9a4\xb2\x01\x05\x08`\x10\xa5\x01\xba\x01\x00\x1a\x0evioleta \xe2\x9d\xa4\xef\xb8\x8fR\x8e\x03\n\xc6\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/d4d0761ed6606f91f15e367aba8ca9a4~tplv-tiktokx-compress_quality_30:64:64.webp?x-expires=1708992000&x-signature=fbm9%2Bbvu3Qg9rqTfkpNoIH%2BHgLg%3D\n\xc2\x01https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/d4d0761ed6606f91f15e367aba8ca9a4~tplv-tiktokx-compress_quality_30:64:64.jpeg?x-expires=1708992000&x-signature=inojqEuQoH3gGTIQoS3whgNiMsU%3D\x82\x02\x00\xb2\x02\x0cvioleta71185\xf2\x02LMS4wLjABAAAAdFEZLCL3SW3L-CqXvfns2QJL7C2VkE8QNMct0DtbTnR2tLgHpkt_sdvBcKZ8XdP4\x1a\x0cVioleta plisr\x02es\x92\x01\x00\x18\x86\x96\xde\x9a\xac\xdc\xb6\xeee0\x01\n\x96\x11\n\x12WebcastChatMessage\x12\xf3\x10\nO\n\x12WebcastChatMessage\x10\xaa\x96\xc3\xf0\xb1\xd9\xb6\xeee\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeee \x93\xef\xdc\xb5\xde10\x01H\x02P\x02z\x07useast5\xb0\x01\x05\xb8\x01\x02\xc0\x01\x02\xc8\x01\x91\xec\xdc\xb5\xde1\x12\xe8\x0c\x08\xab\x88\xad\x92\x90\xb5\xce\xd3e\x1a\x17aaliyahrealisgymnasticsJ\xee\x06\n\xd3\x01https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58~tplv-tiktok-shrink:72:72.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=2ndW%2FIWZRYpRkCZKvl7Dmiv8WEc%3D\n\xc3\x01https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58~c5_100x100.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=EDK5xfOyYJTXdRYl2IyXCsDyBnw%3D\n\xc5\x01https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58~c5_100x100.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=GsWwD2cLG4cq3LGNp96jT%2FlcK5U%3D\n\xc5\x01https://p16-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58~c5_100x100.jpeg?lk3s=a5d48078&x-expires=1709143200&x-signature=z6eTWVpZqx0LOBxYEO62jK%2Bg2qw%3D\x12@100x100/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58R\xdf\x04\n\xc6\x01https://p19-sign.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58~tplv-tiktokx-compress_quality_30:64:64.webp?x-expires=1708992000&x-signature=gKf29xB0eR5JiFBesmjYMHZFQJs%3D\n\xc8\x01https://p16-sign.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58~tplv-tiktokx-compress_quality_30:64:64.webp?x-expires=1708992000&x-signature=YhC2VNorwM9%2BLqtF8HKQm3CcrCM%3D\n\xc8\x01https://p19-sign.tiktokcdn-us.com/tos-useast5-avt-0068-tx/7a0ca09e4ff81232cef6a5bbd452fb58~tplv-tiktokx-compress_quality_30:64:64.jpeg?x-expires=1708992000&x-signature=PV0Mp33FCtXCJI%2BPFC9jeccWVLE%3D\xb2\x01\x06\x08\x17\x10\x0c\x18\x01\xba\x01\x00\x82\x02\x00\xb2\x02\x11aaliyahrealisgymn\xf2\x02LMS4wLjABAAAAteUblZQxnLyP6tA-jUPr4yVNiVpJpUajHOkR87lQ6YwPZTWW5jqvr7NHS4hvChKK\x1a\x02nor\x02en\x92\x01\x02 \x01\x9a\x01\x14\n\x0euser_type_rule\x10\xc0\x9a\x0c\x9a\x01\x18\n\x11community-flagged\x10\xb0\xd2\xae\x03\x9a\x01\x1a\n\x0ecommentator_id\x10\xab\x88\xad\x92\x90\xb5\xce\xd3e\x9a\x01\x12\n\x07default\x10\xe0\x81\xc0\xdd\xd3\xc9\x84\x03\x9a\x01\x10\n\x0bdefault_app\x10\x90N\x9a\x01\x11\n\x06rankV3\x10\xc8\xb6\xa2\xe2\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0fttp_rule_rerank\x10\xc8\xb6\xa2\xe2\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0etimestamp_desc\x10\xb8\xf6\xe7\x8e\xb2\xe5\xcc\xae\x01\x9a\x015\n*tikcast_community_comment_18866_v7_r655069\x10\xc8\xb6\xa2\xe2\xd3\xc9\x84\x03\x9a\x01:\n/tikcast_community_comment_18866_v7_r655069_desc\x10\xc8\xb6\xa2\xe2\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0fidc_rule_rerank\x10\xc8\xea\xab\xf5\xd3\xc9\x84\x03\x9a\x01\x16\n\x0bv13_r712088\x10\xc8\xea\xab\xf5\xd3\xc9\x84\x03\x9a\x01\x16\n\x0bv12_r702075\x10\xc8\xea\xab\xf5\xd3\xc9\x84\x03\x9a\x01\x1a\n\x0fidc_rule_rerank\x10\xc8\xea\xab\xf5\xd3\xc9\x84\x03\xa2\x01\x01\x00\x18\xaa\x96\xc3\xf0\xb1\xd9\xb6\xeee0\x01\n\xd8\x07\n\x12WebcastChatMessage\x12\xb5\x07\x92\x01\x02 \x01\x9a\x01\x12\n\x07default\x10\xf0\x8f\xfc\xde\xd3\xc9\x84\x03\x9a\x01\x10\n\x0bdefault_app\x10\x90N\x9a\x01\x18\n\rbatch_rank_v1\x10\xf0\x96\xa3\xed\xd3\xc9\x84\x03\x9a\x01\x10\n\x05_desc\x10\x80\xd3\xd0\xe0\xd3\xc9\x84\x03\x9a\x01\t\x10\x80\xa6\xee\xdb\xd3\xc9\x84\x03\xa2\x01\x01\x00\nJ\xb8\x01\x02\n\x12WebcastChatMessage\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeeeH\x02P\x02z\x02ie\xb0\x01\x05\xc0\x01\x02\xc8\x01\xfc\x80\xdd\xb5\xde1\x10\xa0\x96\x8d\xae\xc8\xdb\xb6\xeee \xfe\x85\xdd\xb5\xde10\x01\x12\xf0\x05R\x00\xb2\x01\x07\x18\x01\x08\x8f\x05\x10:\xba\x01\x00\x82\x02\x00\xb2\x02\x0fafnan201211juni\x1a\x05AfnanJ\xe9\x04\n\xc7\x01https://p16-pu-sign-ie.tiktokcdn-eu.com/tos-ie-avt-0068-ie/59658e7fd2b29dfd4de2b488a09acf45~tplv-tiktok-shrink:72:72.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=V27iAchvSwXhlaUNE25ewN76eMU%3D\n\xad\x01https://p19-pu-sign-ie.tiktokcdn-eu.com/obj/tos-ie-avt-0068-ie/59658e7fd2b29dfd4de2b488a09acf45?lk3s=a5d48078&x-expires=1709143200&x-signature=IFZDZtnghZBOxDFQGqQTaGLLbcE%3D\n\xaf\x01https://p16-pu-sign-ie.tiktokcdn-eu.com/obj/tos-ie-avt-0068-ie/59658e7fd2b29dfd4de2b488a09acf45?lk3s=a5d48078&x-expires=1709143200&x-signature=yrbCddUeHMqs6WNhLyc%2FI0hIbDA%3D\x12;100x100/tos-ie-avt-0068-ie/59658e7fd2b29dfd4de2b488a09acf45\xf2\x02LMS4wLjABAAAA4t7boMuYG70VDCIbGR1Qhdqn3NKznucRP2F_KyTECpbnzLIa21yAeT_dr369Wnhw\x08\xa1\x88\xdc\x98\xe3\xe8\xfe\xe2e\x1a\x05Afnanr\x02is\x18\xa0\x96\x8d\xae\xc8\xdb\xb6\xeee0\x01\n\xca\x0b\n\x12WebcastChatMessage\x12\xa7\x0b\nP \xfc\x9e\xdd\xb5\xde10\x01H\x02\xb8\x01\x02\xc0\x01\x02\xc8\x01\xe8\x9a\xdd\xb5\xde1\x18\xaa\x96\xaa\xbe\xe5\xb0\xb3\xeee\x10\xa1\x96\xb8\xc2\xe2\xdb\xb6\xeeeP\x02z\x08useast2a\xb0\x01\x05\n\x12WebcastChatMessage\x12\xdb\t\x1a\x0cMyfav_preppyJ\xa5\x05\x12D100x100/tos-useast2a-avt-0068-euttp/36d6e16d5a6d53ee1b2d1e77c1992027\n\xd0\x01https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-euttp/36d6e16d5a6d53ee1b2d1e77c1992027~tplv-tiktok-shrink:72:72.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=dVNKWUstSPmsEL4kYwRB9Q6g5g0%3D\n\xc2\x01https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-euttp/36d6e16d5a6d53ee1b2d1e77c1992027~c5_100x100.webp?lk3s=a5d48078&x-expires=1709143200&x-signature=S8GG7cCoCnlGLZHpKaq8EhevQkM%3D\n\xc4\x01https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-euttp/36d6e16d5a6d53ee1b2d1e77c1992027~c5_100x100.jpeg?lk3s=a5d48078&x-expires=1709143200&x-signature=Qv00LoecuUJVq%2BhSNjBquvcasMY%3D\x82\x02\x00\x08\xa0\x88\xc1\xbc\xd7\xdd\xda\x98eR\xa8\x03\n\xd0\x01https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-euttp/36d6e16d5a6d53ee1b2d1e77c1992027~tplv-tiktokx-compress_quality_30:64:64.webp?x-expires=1708992000&x-signature=g9wQbfb2f9e9EEZICBklBvptIZ8%3D\n\xd2\x01https://p16-sign-useast2a.tiktokcdn.com/tos-useast2a-avt-0068-euttp/36d6e16d5a6d53ee1b2d1e77c1992027~tplv-tiktokx-compress_quality_30:64:64.jpeg?x-expires=1708992000&x-signature=gv%2B4Uf2s1sFsHyASXBNQdqTXMpI%3D\xb2\x01\x07\x08\x8d\x02\x109\x18\x01\xba\x01\x00\xb2\x02\x0esophia_spamz64\xf2\x02LMS4wLjABAAAAhAJUjiOVofAmYDIJmlQ45IbGhy_DQhK925iV7aTh73_wBHXAZwvXQMkQ7AoKv80X\x1a\x06Bueeeer\x02es\x92\x01\x02 \x01\x9a\x01\x12\n\x07default\x10\x88\xf7\xd1\xe0\xd3\xc9\x84\x03\x9a\x01\x10\n\x0bdefault_app\x10\x90N\x9a\x01\x18\n\rbatch_rank_v1\x10\x88\xfe\xf8\xee\xd3\xc9\x84\x03\x9a\x01\x10\n\x05_desc\x10\x80\x80\xb3\xe5\xd3\xc9\x84\x03\x9a\x01\t\x10\x80\xd3\xd0\xe0\xd3\xc9\x84\x03\xa2\x01\x01\x00\x18\xa1\x96\xb8\xc2\xe2\xdb\xb6\xeee0\x01\x12)1708973277105_7339984093934819117_1_1_0_0\x18\xe8\x07 \xb1\xff\xfa\xb5\xde1*\xd9\x01fetch_time:1708973277105|start_time:1708972993281|ack_ids:,7339983114779478827_1d34,7339983381549714222_1dae,7339984026620578603_1ed4|flag:1|seq:1|next_cursor:1708973277105_7339984093934819117_1_1_0_0|wss_info:0-0-0-0X\x01b\x137339982037724564270'

print(WebsocketResponseEvent().parse(data))

### Expected Behaviour
`...`

### Actual Behaviour
*If applicable, include screenshots!*

`...`

### Package Version

My version of TikTokLive is `6.0.1`.

### Operating System

- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

**Comment by isaackogan** [comment]
wtf is this

**Comment by Superheroff** [comment]
![QQ截图20240228230731](https://github.com/isaackogan/TikTokLive/assets/46555936/b2868b6a-c740-4c41-8b20-85946f84c4d2)
