### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by sebm12** [isaackogan/TikTokLive#193]
### Describe the bug

I followed the tutorial, but unfortunately, I'm not getting any output in PyCharm. What could be the issue?

### Operating System

- [ ] Windows
- [ ] Linux
- [X] MacOS
- [ ] Other (Specifically, `...`)

<img width="1395" alt="Bildschirmfoto 2024-03-09 um 18 01 02" src="https://github.com/isaackogan/TikTokLive/assets/162825988/0680c14d-b3dd-443f-822d-c16c4d6e3952">

**Comment by isaackogan** [comment]
Can you paste the code in its entirety for me @sebm12?

I'll check on my end and investigate.

**Comment by isaackogan** [comment]
Closed due to inactivity
