### ISSUE TITLE
I get an error [SIGN_NOT_200]

### ISSUE THREAD

**Issue by KalvinThien** [isaackogan/TikTokLive#194]
### Error description

I get an error [SIGN_NOT_200]

### Expected behavior

'...'

### Actual behavior
*If so, include screenshots!*
![screenshot_1710946570](https://github.com/isaackogan/TikTokLive/assets/120565705/d86d2302-cc0a-4448-9b7f-08b045258061)

### Package version

My TikTokLive version is '6.0.2post1'.

### Operating system

- [ ] Windows

### Anything else

If there is anything else, add it here.

**Comment by isaackogan** [comment]
fixed
