### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by JiehuiSun** [isaackogan/TikTokLive#199]
### Describe the bug

`I followed the tutorial, but unfortunately, I'm not getting any output in PyCharm. What could be the issue?`

### Expected Behaviour

`...`

### Actual Behaviour
*If applicable, include screenshots!*

```python
from TikTokLive import TikTokLiveClient
from TikTokLive.events import ConnectEvent, CommentEvent

# Create the client
client: TikTokLiveClient = TikTokLiveClient(unique_id="@isaackogz")


# Listen to an event with a decorator!
@client.on(ConnectEvent)
async def on_connect(event: ConnectEvent):
    print(f"Connected to @{event.unique_id} (Room ID: {client.room_id}")


# Or, add it manually via "client.add_listener()"
async def on_comment(event: CommentEvent) -> None:
    print(f"{event.user.nickname} -> {event.comment}")


client.add_listener(CommentEvent, on_comment)

if __name__ == '__main__':
    # Run the client and block the main thread
    # await client.start() to run non-blocking
    client.run()
```

### Package Version

My version of TikTokLive is `v6.0.3`.

### Operating System

- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

The same problem as(https://github.com/isaackogan/TikTokLive/issues/193#issue-2177314885)

**Comment by isaackogan** [comment]
For one, @isaackogz is my TikTok, and I don't go live...

**Comment by JiehuiSun** [comment]
您好，邮件已收到。

**Comment by JiehuiSun** [comment]
> For one, @isaackogz is my TikTok, and I don't go live...

Of course, this must be known. I changed the anchor id.

**Comment by isaackogan** [comment]
Could you enable debug by setting the loglevel of to DEBUG, and print your debug?

**Comment by JiehuiSun** [comment]
> Could you enable debug by setting the loglevel of to DEBUG, and print your debug? It may be too large, in which case upload a file to pastebin and send the link.

`client.logger.setLevel("DEBUG")`
After setting the log level, the execution prompt timed out.
![image](https://github.com/isaackogan/TikTokLive/assets/32083752/f2e26dd3-c643-46d2-adda-2b4394145ec3)

**Comment by JiehuiSun** [comment]
```python
client._logger = TikTokLiveLogHandler.get_logger(
      level=LogLevel.DEBUG
)
```
After setting the log level, the execution prompt timed out.
```
TikTokLive.client.web.routes.fetch_sign.SignAPIError: [EMPTY_PAYLOAD] Sign API returned an empty request. Are you being detected by TikTok?
```
Do you need to log in?

**Comment by isaackogan** [comment]
Are you from a country where TikTok is banned?

**Comment by isaackogan** [comment]
Closing in 48h if stale

**Comment by JiehuiSun** [comment]
> Are you from a country where TikTok is banned?
> 
> P.S. The timeout was a coincidence, not sure what causes it for you. `Sign API returned an empty request. Are you being detected by TikTok?` tells me your connection request was blocked.

Yes, but I have no problem on linux. The problem is only on mac. Of course, vpn enabled.
