### ISSUE TITLE
stop tiktokLiveClient

### ISSUE THREAD

**Issue by metalalchemist** [isaackogan/TikTokLive#201]
### Describe the bug
if i write client.disconnect() if i put client.run() says:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback                                               
client don't stop
`...`

### Expected Behaviour
stop TikTokLiveClient
`...`

### Actual Behaviour
client not stop and result are arive in console.
`...`

### Package Version
My version of TikTokLive is 6.0.3`...`.

### Operating System

- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else
in my program the client runs in a thread that i configure  for this reason i put client.run and when i tried disconect it put client.disconect ut this method is asynchronous.

**Comment by isaackogan** [comment]
https://www.youtube.com/watch?v=K56nNuBEd0c
