### ISSUE TITLE
Failed to connect to TikTokLive: [EMPTY_PAYLOAD] Sign API returned an empty request. Are you being detected by TikTok?

### ISSUE THREAD

**Issue by parknich** [isaackogan/TikTokLive#202]
### Describe the bug

Upon connecting, the Sign API sometimes returns an empty request

### Expected Behaviour

It connects successfully

### Actual Behaviour
*If applicable, include screenshots!*

Errors out with:
Failed to connect to TikTokLive: [EMPTY_PAYLOAD] Sign API returned an empty request. Are you being detected by TikTok?

### Package Version

My version of TikTokLive is 6.0.3

### Operating System

- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

**Comment by tthiel1** [comment]
Im having a similar issue, has anyone come up with a solution yet?

**Comment by RyanArmstrong777** [comment]
I'm using proxies and it seems to work fine. make sure you use client.web_proxy and client.ws_proxy

**Comment by Ikaros-521** [comment]
same，use or not use proxy，all this problem

**Comment by isaackogan** [comment]
This issue was fixed by @zerodytrash

All the best,
Isaac
