### ISSUE TITLE
Gift examples doesnt work anymore "count"

### ISSUE THREAD

**Issue by ThePolishDragon** [isaackogan/TikTokLive#204]
Any of provided gift examples doesnt work anymore, there is not anymore any command like: "event.gift.count" or "event.gift.info.name".
Those 2 commands are changed to "event.gift.diamond_count" and "event.gift.name"

**Comment by isaackogan** [comment]
ty

**Comment by isaackogan** [comment]
Fixed in https://github.com/isaackogan/TikTokLive/commit/79a5e26b34f527f85b09faa8137d9d9bf2bf8ea9
