### ISSUE TITLE
Unexpected error fetching when user is offline

### ISSUE THREAD

**Issue by masumr** [isaackogan/TikTokLive#208]
Step to reproduce-

1. User in live
2. Connecting Tiktok Live then event data is comming 
3. User is offline in the mean while we fetch this issue -

![image](https://github.com/isaackogan/TikTokLive/assets/17784661/61ac87e1-5672-4dbc-9ec5-bff93b7ffff1)

### Package Version

My version of TikTokLive is 6.0.3

**Comment by isaackogan** [comment]
Closing if stale in 48h
