### ISSUE TITLE
Failed to fetch room id from Webcast, see stacktrace for more info.

### ISSUE THREAD

**Issue by masumr** [isaackogan/TikTokLive#210]
Last day to still package not provided any event data and generate this issue-  **Failed to fetch room id from Webcast, see stacktrace for more info.**

Step to reporduce-
1. Connect a tiktok live package then find this log and didn't getting any event data

Error trace is given below-
![image](https://github.com/isaackogan/TikTokLive/assets/17784661/99f91b29-43df-49c1-8c97-cb07e03d7d96)

### Package Version

My version of TikTokLive is 4.5.2

**Comment by isaackogan** [comment]
You are blocked by TikTok for spam. Use an HTTP proxy. 

The error is very clear about this:

1. Failed to fetch the room ID from TikTok
2. Response from TikTok is `NoneType`, i.e. None

It is clear TikTok is blocking you and returning nothing in the response, or, perhaps not even completing the response. This is expected TikTokLive behaviour.

**Comment by isaackogan** [comment]
Closing in 48h if stale
