### ISSUE TITLE
GiftEvent triggered twice for one gift

### ISSUE THREAD

**Issue by lduvex** [isaackogan/TikTokLive#211]
I've noticed when one gift is sent, the gift event is triggered twice. This happens about 90% of the time.

Here's my code:

from TikTokLive.client.client import TikTokLiveClient
from TikTokLive.client.logger import LogLevel
from TikTokLive.events import ConnectEvent, GiftEvent

client: TikTokLiveClient = TikTokLiveClient(
    unique_id="@username"
)

@client.on(ConnectEvent)
async def on_connect(event: ConnectEvent):
    client.logger.info(f"Connected to @{event.unique_id}!")

@client.on(GiftEvent)
async def on_gift(event: GiftEvent):
    client.logger.info(f"Recieved gift ID = {event.gift.id}!")
   
if __name__ == '__main__':
    # Enable debug info
    client.logger.setLevel(LogLevel.INFO.value)

    # Connect
    client.run()

**Comment by isaackogan** [comment]
This doesn't really sound like a bug, but rather how streaking is handled by TikTok. Please confirm you are not referring to streakable gifts, like Rose, which always fire a minimum of twice (once to start, once to let you know the streak is over).

**Comment by syumai80** [comment]
Right now "Cap" is a streakable gift, but why is the value of {event.gift.streakable} False?

**Comment by GaskyGod** [comment]
Is there any way to fix it? When they send a rose, the action is done twice

**Comment by isaackogan** [comment]
It is not a bug. There is no "fix". Listen for the streak to finish!
