### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by senseiki** [isaackogan/TikTokLive#213]
![295999070-4b54a3d2-8fd3-4e82-a4f0-d53c2b188baf](https://github.com/isaackogan/TikTokLive/assets/141006157/4a96e77a-db35-44db-9aeb-a2b795faa5ef)
Is it possible to retrieve the data of this object?

**Comment by isaackogan** [comment]
Probably, but that is out of the scope of the library anyways. For this, you have to figure it out yourself. I recommend DevTools.
