### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_type'

### ISSUE THREAD

**Issue by wsjmuffas** [isaackogan/TikTokLive#218]
### Describe the bug
![Uploading 1714204670001.jpg…]()

**Comment by wsjmuffas** [comment]
return super(TikTokLiveClient, self).on(event.get_type(), f)
AttributeError: 'str' object has no attribute 'get_type'

**Comment by isaackogan** [comment]
I believe this was fixed in a commit recently. Please ping me to reopen if I am wrong.
