### ISSUE TITLE
Detecting user exit from live

### ISSUE THREAD

**Issue by rekvizitt** [isaackogan/TikTokLive#219]
Hey, I have a specific requirement where I need to track when users leave a live. I noticed that the library provides a method to capture when a user joins a stream, but I couldn't find a way to determine when they leave. Is there a recommended approach or workaround to achieve this functionality using the TikTokLive library? Ideally, I would like to be able to detect when a user is no longer present in the stream and perform certain actions based on that information. Any guidance or suggestions on how to implement this feature would be greatly appreciated. 🙏🏻

**Comment by isaackogan** [comment]
Not possible, TikTok do not provide that data

**Comment by rekvizitt** [comment]
Thank you, can you suggest if there is a way to get information about all current viewers?

**Comment by isaackogan** [comment]
As a general rule: If you can't see it on TikTok, you can't do it with this lib. We can't make up data.
