### ISSUE TITLE
Error with the GiftEvent

### ISSUE THREAD

**Issue by mikeloski** [isaackogan/TikTokLive#22]
Hi, the GiftEvent doesn't seem to work properly. Usually it works, but sometimes when they send gifts the same error always pops up, see the image: 
https://prnt.sc/9EwlAhlqgLaY
How can this be fixed? Is this happening to other people? 
I hope you can help me, thanks for your attention.

**Comment by isaackogan** [comment]
You need to update your version of the library.

Isaac

**Comment by mikeloski** [comment]
Thanks man, it worked :)
Thank you for your help, I really appreciate it.
