### ISSUE TITLE
Failed request to Sign API with status code 503 and payload "b'{"code":503,"error":"API is not ready for connections yet."}'".

### ISSUE THREAD

**Issue by masumr** [isaackogan/TikTokLive#221]
While starting the event data capturing of a tiktok live, at the first stage , I got the below error. And, after this , no data was being captured. I faced this problem , couple of times! But. no clue why this error happened and how to resolve. Please try to fix this ERROR!

[SIGN_NOT_200] Failed request to Sign API with status code 503 and payload "b'{"code":503,"error":"API is not ready for connections yet."}'".

### Package Version

My version of TikTokLive is 6.0.4

Thanks!

**Comment by isaackogan** [comment]
Fixed.

Long-term please see `#announcements` in the Discord. A major focus of the project is now on achieving stability with the signing server.

Isaac
