### ISSUE TITLE
TikTokLive.client.web.routes.fetch_sign.SignAPIError: [EMPTY_PAYLOAD] Sign API returned an empty request. Are you being detected by TikTok?

### ISSUE THREAD

**Issue by stephen1158686** [isaackogan/TikTokLive#224]
TikTokLive.client.web.routes.fetch_sign.SignAPIError: [EMPTY_PAYLOAD] Sign API returned an empty request. Are you being detected by TikTok?

**Comment by islisong** [comment]
6.0.8 version  appearing again
