### ISSUE TITLE
I'm getting an error when saving my livestream : websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

### ISSUE THREAD

**Issue by KalvinThien** [isaackogan/TikTokLive#227]
```

[TikTokLive] INFO from C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py:612 — ! connect failed again; retrying in 5 seconds
Traceback (most recent call last):
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py", line 598, in __aiter__
    async with self as protocol:
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py", line 325, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200```

**Comment by isaackogan** [comment]
oof. latest version?

**Comment by ajctrl** [comment]
same here

**Comment by KalvinThien** [comment]
> version?

Im use command : pip install TikTokLive --upgrade 
And vs show up is : 6.0.6

**Comment by deepin2soul** [comment]
@zufarrizal did you find solution? - i have the same problem...

**Comment by isaackogan** [comment]
Please confirm this is occurring still, thanks

**Comment by zufarrizal** [comment]
@deepin2soul you can follow my code https://github.com/zufarrizal/MinecraftSurvivalPythonTiktok

**Comment by deepin2soul** [comment]
> @deepin2soul you can follow my code https://github.com/zufarrizal/MinecraftSurvivalPythonTiktok

        elif not response.status_code == 200:
            raise SignAPIError(
                SignAPIError.ErrorReason.SIGN_NOT_200,
                f"Failed request to Sign API with status code {response.status_code} and payload \"{response.read()}\"."
            )

**Comment by zufarrizal** [comment]
> > @deepin2soul you can follow my code https://github.com/zufarrizal/MinecraftSurvivalPythonTiktok
> 
> ```
>     elif not response.status_code == 200:
>         raise SignAPIError(
>             SignAPIError.ErrorReason.SIGN_NOT_200,
>             f"Failed request to Sign API with status code {response.status_code} and payload \"{response.read()}\"."
>         )   
> ```

I found several problems, it seems there is a problem with the API server being full, or usually it also happens in the node version belonging to zerodytrash at certain times, where I usually do it at 7 pm UTC+7 the same thing definitely happens! maybe you can find another way. so I chose another time to run the application.

The most important thing is to run it using your own TikTok. and don't use a proxy or similar to connect.

**Comment by isaackogan** [comment]
Closed due to lack of activity.
