### ISSUE TITLE
 No close frame received or sent

### ISSUE THREAD

**Issue by masumr** [isaackogan/TikTokLive#234]
### Describe the bug
I have been using the tiktok package to connect and retrieve event data. Initially, everything works smoothly and I receive event data as expected. However, after some time, the package stops providing event data and I encounter an error.

### Expected Behavior
The tiktok package should continue to provide event data without interruption.

### Actual Behavior
The tiktok package stops providing event data after some time and an error is encountered.

### Error Message
```
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```
Details is given below  -

![image](https://github.com/isaackogan/TikTokLive/assets/17784661/b042d4ca-ac56-42b3-87d4-62b96332e215)

### Package Version

My testing version of TikTokLive is `6.0.3` , `6.0.4` and `6.0.6`.

### Operating System

- [ ] Linux

**Comment by isaackogan** [comment]
This should be long-fixed in the latest versions. Please re-open the issue if this occurs again **consistently**.
