### ISSUE TITLE
Comment with only emoji's not captured by package

### ISSUE THREAD

**Issue by aCS6** [isaackogan/TikTokLive#237]
Here, a user named 'amir-viva' send a comment that contains only emoji's . 

![image](https://github.com/isaackogan/TikTokLive/assets/71452034/c21c5a1b-f269-426a-95d2-c1a5c70ca9ba)

I wrote all the comments into a log file. But the comment 'amir-viva' was not captured by the package. How should I get such comment ?
![image](https://github.com/isaackogan/TikTokLive/assets/71452034/19375b0a-d8ca-47c8-860a-553344f9eb09)

Or, we never will get this type of comment from the package ?

**Comment by isaackogan** [comment]
Pass sessionid cookie, tiktok is excluding this data

**Comment by aCS6** [comment]
Hey , @isaackogan  , Morning Buddy!
I am not sure , how to pass 'sessionid cookie' . Please assist me how to use it ?
Thanks

**Comment by isaackogan** [comment]
`client.web.set_session_id('754acbe178fd15b172d16d7ce38e27bb')`

**Comment by isaackogan** [comment]
client.web.set_session_id('session_id')
