### ISSUE TITLE
LiveEndEvent not getting called

### ISSUE THREAD

**Issue by bimemto** [isaackogan/TikTokLive#239]
### Describe the bug
When livestream end, I can't receive any live end event

### Expected Behaviour
I am beable to receive live end event when the stream ended

### Package Version

My version of TikTokLive is `6.0.5`.

### Operating System

- [ ] Windows
- [x ] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

**Comment by isaackogan** [comment]
Cannot reproduce, closing.

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/9e9d3df3-0122-4616-973d-286b646f410f">
