### ISSUE TITLE
a complete example? livestream recording and chat events when a user is live?

### ISSUE THREAD

**Issue by vioan** [isaackogan/TikTokLive#241]
Hi,

First, thank you very much for the great library, is really useful and I also enjoy the other projects which are using your library.

As you have examples about "check if a user is live", "writing comments and gifts in a file", and "record the livestream", I am asking why don't you just provide a complete example which is monitoring 24/7 if a user is live (maybe 2-3 mins between checks) and if user is live to record the livestream and in the same time write the corresponding chat events (comments, gifts, ...) in a .txt file, next to the recording?

This will also help your library to grow, as recording the livestream AND the chat events is something what a lot of users are asking in those two projects:

https://github.com/Michele0303/tiktok-live-recorder
https://github.com/go-olive/olive

which do the livestream recording but not the chat events.

Thanks a lot!

**Comment by isaackogan** [comment]
open to the idea
