### ISSUE TITLE
Get TikTok live information without event

### ISSUE THREAD

**Issue by Silme94** [isaackogan/TikTokLive#242]
Is there a way to get live information but with no event? Like for example a function to get the numbers of like or something? For example: 
```py
from TikTokLive import TikTokLiveClient
from TikTokLive.events import ConnectEvent, CommentEvent

# Create the client
client: TikTokLiveClient = TikTokLiveClient(unique_id="@isaackogz")

if __name__ == '__main__':
    # -- Exmaples --
    client.getLikes() # get the numbers of likes
    client.getViewvers() # get the numbers of people who are watching the live
    client.getGift("Rose") # return number of roses
```

**Comment by isaackogan** [comment]
You can grab room info which should have all this.

**Comment by Silme94** [comment]
How? Because when i check the documentation i only see events. By the way i wanna get live information this way so i can just make an api to collect data, for example http://localhost?username=@isaackogz and it returns json data with live information.

**Comment by isaackogan** [comment]
https://isaackogan.github.io/TikTokLive/TikTokLive.client.web.routes.html

**Comment by Silme94** [comment]
can you show me an example?

**Comment by isaackogan** [comment]
No
