### ISSUE TITLE
is any way to connect in a live without username?

### ISSUE THREAD

**Issue by metalalchemist** [isaackogan/TikTokLive#247]
for example if i get a link like:
https://vm.tiktok.com/qweqeoiadjsqqwepqewj/ can i connect to this live paste my link direcly?
note that the link is an example an is not real, but when i share a link in tiktok this is the patern that i get.

**Comment by isaackogan** [comment]
No. 

You must have a username, which you can get by requesting that share link, and parsing the output URL.
