### ISSUE TITLE
Getting always when calling client.is_live() Function<Future at 0x7f0496451ee0 state=pending>

### ISSUE THREAD

**Issue by EinfachGolem** [isaackogan/TikTokLive#249]
### Describe the bug
Everytime i Calling the Function, the return Value is always a Value. So if i try to check it with a If Condition, it will be true. It doesn't matter, if the TikTokUser is live or not
`...`

### Expected Behaviour

`...`

### Actual Behaviour
*If applicable, include screenshots!*

`...`

### Package Version

My version of TikTokLive is `6.0.9`.

### Operating System

- [x] Windows
- [X] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

**Comment by isaackogan** [comment]
...

Please watch a YT tutorial on asyncio, thanks!!
