### ISSUE TITLE
Failed request to Sign API with status code 403 and payload 

### ISSUE THREAD

**Issue by maiductuan** [isaackogan/TikTokLive#262]
i'm run code error, plase support me
TikTokLive.client.web.routes.sign_fetch.SignAPIError: [SIGN_NOT_200] Failed request to Sign API with status code 403 and payload "b'{"code": 403, "error": "This ISP is blocked from accessing the signature service."}'".

**Comment by isaackogan** [comment]
confirm your version

**Comment by isaackogan** [comment]
Self-explanitory

**Comment by maiductuan** [comment]
thank you, because my IP was blocked so I had to use VPN to access
