### ISSUE TITLE
How do you access a person's profile image via TikTokLive?

### ISSUE THREAD

**Issue by teddysgame** [isaackogan/TikTokLive#27]
Like title says, did I miss anything? Do I need to purchase the printer in order to learn how to do this?

**Comment by isaackogan** [comment]
No. God no. I want to be clear that this library is fully open source and you never have to pay a dime to use anything related to it or reading TikTok. All my printer project does is make it easier to do this with fewer lines of code and more efficient code. It builds on top, it is not a part of this.

Please read the docs, they include the answer to your question. https://tiktoklive.isaackogan.com/

You can access it in the user object.
