### ISSUE TITLE
regenerate proto

### ISSUE THREAD

**Issue by isaackogan** [isaackogan/TikTokLive#270]
regenerate proto definitions to add support for https://github.com/isaackogan/TikTokLive/pull/269

**Comment by isaackogan** [comment]
if someone does this and PRs that would be great i can't do it before the 20th

**Comment by steampoweredtaco** [comment]
I looked into this and it uses dynamic loading of the .proto file directly in webcastProtobuf.js; so... I think #269 just works? Neat.

**Comment by isaackogan** [comment]
> I looked into this and it uses dynamic loading of the .proto file directly in webcastProtobuf.js; so... I think https://github.com/isaackogan/TikTokLive/pull/269 just works? Neat.

Unfortunately, this is not JS

**Comment by steampoweredtaco** [comment]
My bad, the PR referenced TikTok live connector and I pulled that repo instead, hahah. Opps

**Comment by isaackogan** [comment]
Done
