### ISSUE TITLE
await client.connect() not finishing when the live is end

### ISSUE THREAD

**Issue by ganlnyn0000** [isaackogan/TikTokLive#271]
### Describe the bug
async def check_loop():
    # Run 24/7
    while True:

        # Check if they're live
        while not await client.is_live():
            client.logger.info("Client is currently not live. Checking again in 60 seconds.")
            await asyncio.sleep(60)  # Spamming the endpoint will get you blocked

        # Connect once they become live
        client.logger.info("Requested client is live!")
        await client.connect()
        client.logger.info("client.connect end!")

### Expected Behaviour
 await client.connect() not finishing when the live is end
 how can I finish await client.connect() when the live is end？thanks a lot!

### Package Version

 6.1.6

### Operating System

 Windows

**Comment by isaackogan** [comment]
Fixed, thanks @int3debug
