### ISSUE TITLE
How to change the language of the events?

### ISSUE THREAD

**Issue by rwmb** [isaackogan/TikTokLive#275]
Is there an example code on how to change the language of the events and gift names like you can do in the node version of this app with:
```javascript
clientParams: {
    "app_language": "en-US",
    "device_platform": "web"
},
```
?
I haven't had time to test if the gift names change, but it seems like it does based on the param.

**Comment by bearbarmaley** [comment]
add your Location in web_presets.py:32
set your location in web_settings.py.py:16

**Comment by rwmb** [comment]
@bearbarmaley thanks for the help! This consists in me changing the package code right? It means I will have to change this every time I update or reinstall the package?

**Comment by bearbarmaley** [comment]
unfortunately yes, but you can implement a parameter as you want and create
a pull request ;)

чт, 5 дек. 2024 г., 01:08 Richard William ***@***.***>:

**Comment by rwmb** [comment]
Awesome. I just wanted to be sure because Python is not really my thing yet. Thanks a lot! If I have the time I will implement this correctly + the feature to not get the list of past 6 - 10 messages when connecting, which I believe is also not implemented here yet.

**Comment by isaackogan** [comment]
Right, so I've fixed this for you in https://github.com/isaackogan/TikTokLive/commit/30f58c1e557133a9d1ee2724cc22ce5b7ab09cb3.

```python
client = TikTokLiveClient(
    unique_id="@tv_asahi_news",
    web_kwargs={
        "httpx_kwargs": {
            "params": {
                "app_language": "en-US",
                "device_platform": "web"
            }
        }
    }
)
```
