### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by jordanbr20** [isaackogan/TikTokLive#278]
### Describe the bug

Some unique_ids (@usernames) work and some don't. 

When I use a username that does work, it provides an API not ready error.

### Expected Behaviour

For it to work

### Actual Behaviour

Username issue:
 I try mine, and get "UserNotFoundError", try a random user, and it finds it..

Username found, but error:
`"[SIGN_NOT_200] Failed Request to sign API with status code 503 and payload "b'{"code":503,"message":"API is not ready for connections yet."}'".`

### Package Version

Fresh Install of Python 3.11.9 64Bit (using pyenv)

Version: 6.2.1.post1
Summary: TikTok Live Python Client
Home-page: https://github.com/isaackogan/TikTokLive
Author: Isaac Kogan
Author-email: info@isaackogan.com

### Operating System

Windows 10

### Anything Else

I have tried just [the examples](https://github.com/isaackogan/TikTokLive/tree/master/examples) so far but can't get past these error to even attempt custom.

I am behind a proxy so I did attempt adding the below to TikTokLiveClient but it did not change anything. ( I used the [Proxy Example](https://github.com/isaackogan/TikTokLive/blob/master/examples/proxying.py))
web_proxy=Proxy("ADDRESS:PORT", auth=("USER","PASSWORD"))

**Comment by hookcide** [comment]
i have the same error code since today 
[SIGN_NOT_200] Failed request to Sign API with status code 503 and payload "b'{"code":503,"message":"API is not ready for connections yet."}'".

**Comment by jordanbr20** [comment]
@isaackogan why was this closed when its still happening?

**Comment by isaackogan** [comment]
Because it isn't a library issue & at the time it was fixed. Also as of writing this now it isn't occurring.

If you get a 503, ping me in Discord. It isn't a library issue.

**Comment by qrq** [comment]
i get this error just now :

Exception: [SIGN_NOT_200] Failed to sign a request due to an error.
