### ISSUE TITLE
Error while running check_live.py example

### ISSUE THREAD

**Issue by drehtisch** [isaackogan/TikTokLive#279]
### Describe the bug

When running python check_live.py it crashes with following error message:

Traceback (most recent call last):  
  File "[..]/check_live.py", line 7, in <module>  
    client: TikTokLiveClient = TikTokLiveClient(  
  File "[..]/.local/lib/python3.10/site-packages/TikTokLive/client/client.py", line 63, in __init__  
    self._web: TikTokWebClient = TikTokWebClient(  
  File "[..]/.local/lib/python3.10/site-packages/TikTokLive/client/web/web_client.py", line 34, in __init__  
    super().__init__(**kwargs)  
TypeError: TikTokHTTPClient.__init__() got an unexpected keyword argument 'proxy'

### Expected Behaviour

Does not crash

### Actual Behaviour
*If applicable, include screenshots!*

`...`

### Package Version

My version of TikTokLive is `TikTokLive-6.3.0.post1`.

### Operating System

- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

**Comment by drehtisch** [comment]
Error doesn't occur when downgraded to `TikTokLive-6.3.0`

**Comment by isaackogan** [comment]
Fixed in https://github.com/isaackogan/TikTokLive/commit/54f4dd091b56e1789c6b2746b733c7e3ed37c171.

Upgrade with `pip install --upgrade TikTokLive==6.3.0.post2`.
