### ISSUE TITLE
Live downloads

### ISSUE THREAD

**Issue by spinningsand** [isaackogan/TikTokLive#29]
Is there a way to download the live itself or to access/download live replays?

**Comment by isaackogan** [comment]
No, this feature does not exist on TikTok.

**Comment by spinningsand** [comment]
There are live replays (or at least there were)  on there, but I don't know if anyone uses them.

**Comment by n000b-n000b** [comment]
> 

Might be able to help make downloading possible.

**Comment by isaackogan** [comment]
> No, this feature does not exist on TikTok.

Oh to be wrong

**Comment by isaackogan** [comment]
Live downloading will be available in the next update. 

See GoTikTokLive: https://github.com/Davincible/gotiktoklive/commit/dda499f27e6d22d4eff860be6cd6553483138f5f

**Comment by isaackogan** [comment]
Released in v4.2.0
