### ISSUE TITLE
Not getting events anymore.

### ISSUE THREAD

**Issue by littleferris** [isaackogan/TikTokLive#42]
**Describe the bug**
I am just not getting comments or other events coming through. I can connect and I get a room id but thats it.
**To Reproduce**

**Expected behavior**
comments and likes to be printed out.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by littleferris** [comment]
I see there was an update, but I am not quite sure what I need to update in my code to get it working again...

**Comment by littleferris** [comment]
I figured out the temp fix but it looks like it only temporarily works. I will either wait for an official fix or rewrite in like javascript.

**Comment by isaackogan** [comment]
pip install TokTokLive --upgrade
