### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by lunat1k-12** [isaackogan/TikTokLive#54]
TikTokLive.types.errors.InitialCursorMissing: Missing cursor in initial fetch response.
Can't connect to the Tik-Tok

**Comment by Daviko290** [comment]
the same thing happened to me you have to update 'pip install TikTokLive --upgrade'

**Comment by kevinyasuo** [comment]
ERROR:root:Traceback (most recent call last):
  File "F:\Programs\Python\Python310\lib\site-packages\TikTokLive\client\base.py", line 253, in __try_websocket_upgrade
    connection: WebSocketClientConnection = await websocket_connect(
tornado.websocket.WebSocketError: Non-websocket response

**Comment by brogrammer1337** [comment]
Same problem here.

Must be because TikTok has blocked it today. The code from the other repo with JavaScript only works if you provide a SessionId and use request polling instead of web socket connection.

**Comment by isaackogan** [comment]
> Same problem here.
> 
> Must be because TikTok has blocked it today. The code from the other repo with JavaScript only works if you provide a SessionId and use request polling instead of web socket connection.

Update.

`pip install TikTokLive --upgrade`
