### ISSUE TITLE
I have upgraded to the latest version! I have encountered such a problem and how should I solve it

### ISSUE THREAD

**Issue by kevinyasuo** [isaackogan/TikTokLive#55]
ERROR:root:Traceback (most recent call last):
  File "F:\Programs\Python\Python310\lib\site-packages\TikTokLive\client\base.py", line 253, in __try_websocket_upgrade
    connection: WebSocketClientConnection = await websocket_connect(
tornado.websocket.WebSocketError: Non-websocket response

**Comment by isaackogan** [comment]
Full traceback or I cannot help you.

**Comment by kevinyasuo** [comment]
![image](https://user-images.githubusercontent.com/101216256/181849625-b953f104-226b-4a9c-8d55-4fec6e9af59e.png)
It works fine for a few seconds at first and then stops accepting messages

**Comment by isaackogan** [comment]
Remove your added headers and sessionid in client.run()

**Comment by kevinyasuo** [comment]
![image](https://user-images.githubusercontent.com/101216256/181851362-2154b9a8-59b3-4e87-add9-cb47f64fe490.png)

**Comment by isaackogan** [comment]
Remove. The. Extra. Headers.

**Comment by kevinyasuo** [comment]
It's getting this error while it's working
![image](https://user-images.githubusercontent.com/101216256/181852372-65ecc918-5070-4ca9-a8e2-011ed7328d29.png)

**Comment by isaackogan** [comment]
Use gift.giftDetails.giftName

Reference the docs: https://isaackogan.github.io/TikTokLive/TikTokLive.types.html#TikTokLive.types.objects.GiftDetails

**Comment by kevinyasuo** [comment]
Thank bro
