### ISSUE TITLE
No bug display. No error output. Just randomly misses a few gifts and comments. Sometimes nothing displays at all.

### ISSUE THREAD

**Issue by kosmicforger** [isaackogan/TikTokLive#56]
**Describe the bug**
It doesn't get all comments and gifts. 

**To Reproduce**
1. Compile python code
2. Run exe on CMD, "TikTokMonitor.exe (username)" without the parenthesis

**Expected behavior**
To catch all gifts and comments

**Code**
`from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import GiftEvent, ShareEvent, LikeEvent, FollowEvent, ConnectEvent, CommentEvent

client = TikTokLiveClient(sys.argv[1])

@client.on("gift")
async def on_gift(event: GiftEvent):
    if event.gift.gift_type == 1 and event.gift.repeat_end == 1:
        output = (f"Gift,{event.user.profilePicture.avatar_url},{event.user.uniqueId},{event.gift.repeat_count},{event.gift.extended_gift.name},{event.gift.giftDetails.giftImage.giftPictureUrl},{event.gift.giftDetails.diamondCount}")
        print(output.encode("utf-8"),flush=True)

    elif event.gift.gift_type != 1:
        output = (f"Gift,{event.user.profilePicture.avatar_url},{event.user.uniqueId},1,{event.gift.extended_gift.name},{event.gift.giftDetails.giftImage.giftPictureUrl},{event.gift.giftDetails.diamondCount}")
        print(output.encode("utf-8"),flush=True)

@client.on("like")
async def on_like(event: LikeEvent):
    if event.likeCount > 10:
        output = (f"Like,{event.user.profilePicture.avatar_url},{event.user.uniqueId},{event.likeCount}")
        print(output.encode("utf-8"),flush=True)

@client.on("share")
async def on_share(event: ShareEvent):
    output = (f"Share,{event.user.profilePicture.avatar_url},{event.user.uniqueId}")
    print(output.encode("utf-8"),flush=True)

@client.on("follow")
async def on_follow(event: FollowEvent):
    output = (f"Follow,{event.user.profilePicture.avatar_url},{event.user.uniqueId}")
    print(output.encode("utf-8"),flush=True)

@client.on("comment")
async def on_follow(event: CommentEvent):
    output = (f"Comment,{event.user.profilePicture.avatar_url},{event.user.uniqueId},{event.comment}")
    print(output.encode("utf-8"),flush=True)

client.run()`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I also noticed that some gifts and comments misses out on browser (chrome)

**Comment by klssem** [comment]
For me it works for a few moments and then it just stops.

**Comment by kosmicforger** [comment]
> For me it works for a few moments and then it just stops.

That happens on mine too, everything is updated. It just stops after a while, and misses a few gifts and comments while it's running.

**Comment by isaackogan** [comment]
First you definitely do not need to encode as UTF 8 or enable flush.

Also, please surround your stuff in \`\`\` these symbols please. 
```code should read like this```
not like this

Without properly formatted code I cannot tell you if it is you our the library.
It should not miss gifts/comments, but disconnecting is possible and noted.

**Comment by RaphaelDxSale** [comment]
Hey @isaackogan  thank you for the repo first of all! 

Also, just a quick question similar to this thread... 

I am getting a strange error that look like the following 

``` TikTokLive.types.errors.FailedConnection: Long polling is not available: Try adding a sessionid as an argument in start() or run() ```

**Comment by isaackogan** [comment]
> Hey @isaackogan thank you for the repo first of all!
> 
> Also, just a quick question similar to this thread...
> 
> I am getting a strange error that look like the following
> 
> `TikTokLive.types.errors.FailedConnection: Long polling is not available: Try adding a sessionid as an argument in start() or run()`
> 
> The data fetches for about 1 second before it stops

looks like you disabled websockets

**Comment by RaphaelDxSale** [comment]
> > Hey @isaackogan thank you for the repo first of all!
> > Also, just a quick question similar to this thread...
> > I am getting a strange error that look like the following
> > `TikTokLive.types.errors.FailedConnection: Long polling is not available: Try adding a sessionid as an argument in start() or run()`
> > The data fetches for about 1 second before it stops
> 
> looks like you disabled websockets

You are correct, I think M1 Macbooks block websockets.. I am not familiar with these anyway.
I tried the exact same code on windows and it worked like a charm. Thanks!

**Comment by isaackogan** [comment]
Resolved in https://github.com/isaackogan/TikTokLive/issues/57
