### ISSUE TITLE
how to respond to certain gifts when send? 

### ISSUE THREAD

**Issue by Subjoel** [isaackogan/TikTokLive#59]
like how to for example make a screenhot when someone send a rose, or play a sound only on gg gift?

**Comment by isaackogan** [comment]
[img]https://i.imgur.com/RpH2Mj6.jpg[/img]

Visit the documentation and examples folder which describe the exact use case of what you are doing.

**Comment by Subjoel** [comment]
bro i need all the gift names so i can do like:
if gift = 'rose':
myfunction()

i cant find the gift names anywhere

**Comment by isaackogan** [comment]
Read the documentation website.
