### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by kosmicforger** [isaackogan/TikTokLive#62]
`File "C:\Users\NOEL GARCIA\AppData\Local\Programs\Python\Python37\lib\site-packages\TikTokLive\client\client.py", line 48, in _on_error
    raise append from original
TikTokLive.types.errors.FailedConnection: Invalid type for url.  Expected str or httpx.URL, got <class 'NoneType'>: None`

**Comment by isaackogan** [comment]
Fixed
