### ISSUE TITLE
is_subscriber is not work! subscribing user comments it doesn't return True. 

### ISSUE THREAD

**Issue by kevinyasuo** [isaackogan/TikTokLive#68]
![image](https://user-images.githubusercontent.com/101216256/188252475-0d43c61e-9987-4c66-b0f8-b0b05c135bd2.png)
![image](https://user-images.githubusercontent.com/101216256/188252479-8c27e577-ff5d-46b2-b783-dcc224708041.png)
I've tried changing the name here, but it still doesn't work!

**Comment by zerodytrash** [comment]
Subscriber badge URLs no longer contain the keyword "sub". There is now a `badgeSceneType` property in TikToks internal protobuf schema that can be used to determine the sub status.

See https://github.com/zerodytrash/TikTok-Live-Connector/commit/25752a9cb25ebe2b14209e487aa7e95ce4a8d6d2

**Comment by isaackogan** [comment]
Fixed in https://github.com/isaackogan/TikTokLive/commit/cdf0daf90adcf58fa8c81edadb6d65485bc5dcae
