### ISSUE TITLE
Trying to get Like Count.... 

### ISSUE THREAD

**Issue by themindfactory** [isaackogan/TikTokLive#7]
I have found a variable called likeCount inside the like event... but it seems to not make sense the # it returns....

Is Like Count possible?

Thanks!

**Comment by themindfactory** [comment]
I search through the source code and found the answer now....

totalLikeCount :-)

Thanks the code is running perfectly!

**Comment by isaackogan** [comment]
I was about to dive into it to find the exact location myself. Mind posting the location for future reference for other people? I will close the issue but leave it unlocked :)

**Comment by Pabloka012** [comment]
Hello!Not sure how to set a person to print Like only once ... don't print them all if you always print like?

**Comment by isaackogan** [comment]
With code, my friend, with code.

**Comment by Pabloka012** [comment]
> 
My friend, how can I write to you, privately. I need help. thank you very much.Regular Items / Text Command System
?
