### ISSUE TITLE
Missing cursor in initial fetch response.

### ISSUE THREAD

**Issue by xSoczek** [isaackogan/TikTokLive#74]
Windows 10 
Code: https://github.com/isaackogan/TikTokLive/blob/master/examples/basic.py
Version 4,3.7

Error:
TikTokLive.types.errors.FailedConnection: Missing cursor in initial fetch response.

**Comment by Gedehamsen021** [comment]
any news?

**Comment by isaackogan** [comment]
No

**Comment by xSoczek** [comment]
Do you have the same problem?

**Comment by HSY777** [comment]
same problem

**Comment by isaackogan** [comment]
This is an issue with TikTok blocking the token signatures required to access Webcast and read from TikTok LIVE. Steps are being taken to return service, but it may be a while.

**Comment by undfndV** [comment]
same problem, just wait

**Comment by Gedehamsen021** [comment]
praying for fix

**Comment by isaackogan** [comment]
Hey guys, TikTokLive has been fixed. You can read about it [here](https://github.com/isaackogan/TikTokLive/issues/75). No update to the package is required.

##  Supporting Development

TikTokLive has always been free to use and free for me to run. As of this most recent fix, it now *actively costs* to run this library, thanks to our new method which should be harder to patch. 

If you enjoy this library, and perhaps you've even made a coin or two thanks to it, consider supporting its development with a donation at https://www.paypal.me/isaackogan. 

For transparency, half of donations following this announcement will go to [Zerody](https://github.com/zerodytrash/), the other developer responsible for running [TikTok-Live-Connector](https://github.com/zerodytrash/TikTok-Live-Connector/).
