### ISSUE TITLE
Multiple cookies exist with name=ttwid

### ISSUE THREAD

**Issue by nikita36trinta** [isaackogan/TikTokLive#76]
Run a simple programm

from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import CommentEvent, ConnectEvent, GiftEvent

client: TikTokLiveClient = TikTokLiveClient(unique_id="@xxx")

@client.on("gift")
async def on_gift(event: GiftEvent):
if event.gift.gift_type == 1:
        if event.gift.repeat_end == 1:
            print(f"{event.user.uniqueId} sent {event.gift.repeat_count}x \"{event.gift.extended_gift.name}\"")
elif event.gift.gift_type != 1:
        print(f"{event.user.uniqueId} sent \"{event.gift.extended_gift.name}\"")

if __name__ == '__main__':
    client.run()

Error occurs:
Exception has occurred: FailedConnection
Multiple cookies exist with name=ttwid

**Comment by Tenetri** [comment]
the code is broken for everyone right now. We're all patiently waiting for a fix.

**Comment by nikita36trinta** [comment]
> the code is broken for everyone right now. We're all patiently waiting for a fix.

Turned out that fix [released](https://github.com/zerodytrash/TikTok-Live-Connector/issues/66#issuecomment-1268913830). That's why i created this one.

**Comment by Tenetri** [comment]
> 

omg thank you! Not sure why you're running into this error, my apologies

**Comment by isaackogan** [comment]
Fixed on the signing server end.

**Comment by nikita36trinta** [comment]
@isaackogan
However the bag still remains. Did the upgrade thing, no difference. I would appreciate your help.
