### ISSUE TITLE
Comments display only after restarting the library

### ISSUE THREAD

**Issue by koffeemate** [isaackogan/TikTokLive#78]
**Describe the bug**
If you launch the library, and comment on your live, everything is ignored (nothing happens at all). After exiting the library, and starting it again, all the comments and other events are spammed in one go.

**To Reproduce**
1. Launch library with username and sessionID
2. Comment on that live, or do any other interaction at all.
3. Nothing happens, the library doesn't detect anything (No events fired at all)
4. Close the library (Or compiled version)
5. Restart the library (Or compiled version) with the exact same input on step 1
6. It should spam you with everything that happened before exiting the library.

**Desktop (please complete the following information):**
 - Windows 10
 - Latest version

**Comment by isaackogan** [comment]
This is likely an issue with you being detected by TikTok. Try a different IP. Comment again on this issue if the new version coming out today/tomorrow doesn't solve your problem. I will close this if it is stale by the 16th of October

**Comment by isaackogan** [comment]
Changed my mind, re-open the issue if it still happens after the next version releases today.
