### ISSUE TITLE
add request_polling_interval_ms to the client constructor

### ISSUE THREAD

**Issue by joachimschwarzschild** [isaackogan/TikTokLive#8]
Hi,

if i add the additional options to the client constructor i get following error:

client: TikTokLiveClient = TikTokLiveClient(
    unique_id="@oldskoldj", **(
        {
            "process_initial_data": True,
            "fetch_room_info_on_connect": True,
            "enable_extended_gift_info": False,
            "request_polling_interval_ms": 1000,
            "client_params": {},
            "request_headers": {}
        }
    )
)

ERROR:

**aseClient.__init__() got an unexpected keyword argument 'request_polling_interval_ms'**

**Comment by isaackogan** [comment]
This was not an issue with the lib, but rather outdated documentation. See master branch for updated documentation.
