### ISSUE TITLE
@client.on("subscribe") does not trigger Subscribe events

### ISSUE THREAD

**Issue by SamiFala** [isaackogan/TikTokLive#83]
**Describe the bug**
In the event  @client.on("subscribe") nothing happens when someone subscribes

**Comment by isaackogan** [comment]
This is really hard to test. Subscribing doesn't happen very often & costs quite a bit to do.

Will look into & update you but it might be a bit.

**Comment by SamiFala** [comment]
Hello,

Wondering if this issue has any udpate ? Thanks

**Comment by isaackogan** [comment]
No update

**Comment by SamiFala** [comment]
Any update ?

**Comment by zerodytrash** [comment]
TikTok sends out the subscribe event only with streamer auth. Means it can help to set the session cookies of the streamer (not tested).

**Comment by isaackogan** [comment]
Subscribe event will be removed in the next update assuming a solution is not found until a reliable subscriber event can be obtained

**Comment by isaackogan** [comment]
No it doesn't

**Comment by isaackogan** [comment]
End-all-be-all: Subscription info only works when **account authentication** details are provided. Until a day when TikTok changes this, there is nothing I can do.
