### ISSUE TITLE
Cancelling an overlapped future failed

### ISSUE THREAD

**Issue by diego-fmachado** [isaackogan/TikTokLive#86]
> Cancelling an overlapped future failed
future: <_OverlappedFuture pending overlapped=<pending, 0x274a414b520> cb=[_ProactorReadPipeTransport._loop_reading()]>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 71, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] The handle is invalid

I'm on Windows 11, Python 3.10.7.
I did some search on this, they say python changed the default event loop implementation on windows since 3.8 or so, some fixes mentions reverting to the old one using `asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`

**Comment by isaackogan** [comment]
Propose a change, can't look into atm
