### ISSUE TITLE
send message function is not working

### ISSUE THREAD

**Issue by Toneq** [isaackogan/TikTokLive#88]
send message function is not working.

- Tried connecting to User B's live using User A's sessionid: "Your SessionId has expired. Please provide a new one" error, but checking sessionid in Dev Tools shows the session hasn't actually expired.
- Tired connecting to User A's live using User A's sessionid: no responses showing up in chat, no errors given from function

**Comment by isaackogan** [comment]
1. Update package
2. Not really supported anymore without you giving your own signatures
