### ISSUE TITLE
Question - Can I reuse the code in yt-dlp (Unlicence)

### ISSUE THREAD

**Issue by upintheairsheep** [isaackogan/TikTokLive#89]
I would like to reuse your code in yt-dlp, one of the most popular video downloaders on the planet, and the go-to video archival tool. Problem is, I would need to licence the re-used code under the Unlicence, which is the same as MIT Licence as it still gives you every right possible except liability, but the licence makes it under public-domain. Do you consent?

**Comment by isaackogan** [comment]
Hi,

You have my explicit consent to do this. Thank you for asking!

Isaac
