### ISSUE TITLE
On error nothing happend.   

### ISSUE THREAD

**Issue by BILINGBALL** [isaackogan/TikTokLive#90]
@client.on("error")
async def on_error(error: Exception):
print(error)

if isinstance(error,
(WebsocketConnectionFailed,FailedFetchRoomInfo,FailedHTTPRequest,FailedConnection,LiveNotFound,FailedParseUserHTML,FailedConnection,)):
print("Handle Some Error")
return

Is there anything wrong with such usement? It can't handle the error, even trigger the handler

And I saw the code of base, it went to @client.on -> base -> on  and did trigger the f but the f is an Exception not solve as event I think

**Comment by isaackogan** [comment]
Not sure, not enough information provided
