### ISSUE TITLE
Connection lost to the Webcast Websocket Server

### ISSUE THREAD

**Issue by SamiFala** [isaackogan/TikTokLive#91]
Hello there ! I sometimes got a problem with the library and need to stop / start again manually when I get this error : 

`'Connection was lost to the Webcast Websocket Server. Restart the client connection to continue.'`

Is there a way to reload everything programatically when this happens ? And do you have and idea of why is this happening ? 
Thanks !

**Comment by isaackogan** [comment]
Hi,

Listen for the disconnect event and reconnect the client
