### ISSUE TITLE
TikTokLive.types.errors.FailedConnection: Error parsing message

### ISSUE THREAD

**Issue by Summer961211** [isaackogan/TikTokLive#94]
TikTokLive.types.errors.FailedConnection: Error parsing message

**Comment by io1337HAPO** [comment]
on pc A: the connection is not stable. One time it can be connected, another time the same issue
on pc B: the connection is stable
on pc C: can't connect

**Comment by Summer961211** [comment]
What's the solution?

**Comment by io1337HAPO** [comment]
My solution is: switch to javascript TikTokLive Connector

**Comment by isaackogan** [comment]
I'm sorry are these two issues related? It looks like you commented an issue on someone else's

**Comment by isaackogan** [comment]
Also, please show the entire stacktrace omg

**Comment by isaackogan** [comment]
Closed due to no further info
