### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by aerarslan** [isaackogan/TikTokLive#98]
**Describe the bug**
I am getting a RuntimeError: This event loop is already running error after I run the code below.

**To Reproduce**
Here is my code:

```
from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import CommentEvent

client: TikTokLiveClient = TikTokLiveClient(
    unique_id="lolmicv", **(
        {
            "enable_extended_gift_info": True
        }
    )
)

@client.on("comment")
async def on_comment(event: CommentEvent):
    print(f"{event.user.uniqueID} -> {event.comment}")
    
if __name__ == '__main__':
    client.run() 
```

**Expected behavior**
Printing the comments of people on that live.

**Desktop (please complete the following information):**
Windows 10, Anaconda

**Additional context**
Here is the full version of the error i am getting:

```
runcell(0, 'C:/Users/arasu/Desktop/tiktok_live/tiktok_live.py')
Traceback (most recent call last):

  File "C:\Users\arasu\anaconda3\envs\tiktok_test\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\arasu\desktop\tiktok_live\tiktok_live.py", line 17, in <module>
    client.run()

  File "C:\Users\arasu\anaconda3\envs\tiktok_test\lib\site-packages\TikTokLive\client\base.py", line 483, in run
    self.loop.run_until_complete(self._connect(session_id=session_id))

  File "C:\Users\arasu\anaconda3\envs\tiktok_test\lib\asyncio\base_events.py", line 563, in run_until_complete
    self._check_runnung()

  File "C:\Users\arasu\anaconda3\envs\tiktok_test\lib\asyncio\base_events.py", line 523, in _check_runnung
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running
```

**Comment by isaackogan** [comment]
Hello, can you tell me what version of Python you are using? Cannot reproduce on 3.8

**Comment by isaackogan** [comment]
Also works in 3.11.....

**Comment by aerarslan** [comment]
i am using a pretty old version of anacondo for workplace purposes. I tested the code with 3.7 and 3.8. they both are giving me the same error. if it is working in your environment, it should be related to my environment. I will update my environment in some weeks and test it. Thank you for the response. If this code piece worked in your environment, this is enough for me.

**Comment by isaackogan** [comment]
Hi, yes, the library only supports >3.8 at the moment. It is likely you could solve your issue in 3.7 by using the following code snippet, though I do not have time to test it:

```
import asyncio

from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import CommentEvent

loop = asyncio.get_running_loop()

client: TikTokLiveClient = TikTokLiveClient(
    loop=loop,
    unique_id="jakeandrich", **(
        {
            "enable_extended_gift_info": True
        }
    )
)


@client.on("comment")
async def on_comment(event: CommentEvent):
    print(f"{event.user.uniqueId} -> {event.comment}")


if __name__ == '__main__':
    client.run()
```

It seems that the loop is already running. Thus, it stands to reason if you just 'get' the loop, the error should go away.

**Comment by aerarslan** [comment]
thank you for the answer. I tried the code you suggested but i am still getting the exact same error. i think it will be better to test it after i update my environment. i will also test the nest-asyncio but i think i tried it before. i was getting a similar error with it. my environment is super old so i think this is the reason it is not working.
